#!/usr/bin/env python3
"""
regenerate_articles.py — Regenerates content for existing Shopify blog articles
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This script fetches existing published blog articles from Shopify and regenerates
their content using the same AI-driven pipeline as `weekly_trend_blog.py` and
`blog_daily.py`. It ensures that the regenerated content aligns with Google
Discover and E-E-A-T standards, including fresh HTML, SEO metadata, and
featured image collages.

For each article:
  1. A relevant product and article format are selected based on the store's catalog.
  2. New, Discover-ready HTML content is generated by AI (using Flipboard trend data via `weekly_trend_blog.py`).
  3. SEO metafields (title_tag, description_tag) are set.
  4. A featured image collage is created and uploaded.
  5. The article's handle (URL) is compared with a newly suggested handle.
  6. If the handle changes, a 301 redirect is created from the old URL to the new one.
  7. The article is updated on Shopify with the new content and metadata.

Usage:
  python scripts/regenerate_articles.py --dry-run        # Preview changes, no Shopify writes
  python scripts/regenerate_articles.py --force          # Regenerate ALL articles
  python scripts/regenerate_articles.py --article-id 123 # Regenerate one specific article
  python scripts/regenerate_articles.py --force --batch-size 20 --batch-index 0 # Batch processing
"""

import os, sys, re, time, random, json, argparse
from datetime import datetime
from pathlib import Path
from urllib.parse import quote, urlparse
from io import BytesIO

import requests
from bs4 import BeautifulSoup

# ── Path setup ─────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT   = SCRIPT_DIR.parent
LOG_DIR     = REPO_ROOT / "logs"
LOG_DIR.mkdir(exist_ok=True)

sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(REPO_ROOT))

import ai_client
from secrets_manager import inject_to_env, get_secret
import weekly_trend_blog as wtb
from weekly_trend_blog import generate_single_article_content

inject_to_env()

# ── Shopify credentials ────────────────────────────────────────────────────────
SHOP    = get_secret("SHOPIFY_STORE")
TOKEN   = get_secret("SHOPIFY_ACCESS_TOKEN")
API_VER = "2024-10"
BASE    = f"https://{SHOP}/admin/api/{API_VER}"
HEADERS = {"X-Shopify-Access-Token": TOKEN, "Content-Type": "application/json"}
STORE_URL = get_secret("STORE_BASE_URL") or f"https://{SHOP}"

if not TOKEN:
    sys.exit("ERROR: SHOPIFY_ACCESS_TOKEN not set.")

YEAR  = datetime.now().year
MONTH = datetime.now().strftime("%B %Y")
TODAY = datetime.now().strftime("%Y-%m-%d")

def _req(method: str, url: str, **kw):
    for attempt in range(5):
        try:
            r = getattr(requests, method)(url, headers=HEADERS, timeout=30, **kw)
            if r.status_code == 429:
                wait = int(float(r.headers.get("Retry-After", 4)))
                print(f"    [rate-limit] sleeping {wait}s…")
                time.sleep(wait)
                continue
            return r
        except requests.exceptions.ConnectionError:
            time.sleep(3 * (attempt + 1))
    raise RuntimeError(f"{method.upper()} {url} failed after 5 attempts")
def _extract_h1(html: str, fallback: str) -> str:
    m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.IGNORECASE | re.DOTALL)
    return re.sub(r"<[^>]+>", "", m.group(1)).strip() if m else fallback

def get_all_blogs() -> list:
    r = _req("get", f"{BASE}/blogs.json")
    r.raise_for_status()
    return r.json().get("blogs", [])

def get_or_create_blog(product_type: str, all_blogs: list, dry_run: bool = False) -> dict:
    ptype_lower = (product_type or "").lower()
    
    # 1. Direct target blog names mapping
    target_blog_title = None
    if "dress" in ptype_lower:
        target_blog_title = "dresses"
    elif any(x in ptype_lower for x in ["jean", "denim", "jort"]):
        target_blog_title = "jeans"
    elif any(x in ptype_lower for x in ["skirt", "skort"]):
        target_blog_title = "skirts"
    elif any(x in ptype_lower for x in ["pant", "legging", "short"]):
        target_blog_title = "pants"
    elif any(x in ptype_lower for x in ["top", "blouse", "shirt", "tee", "t-shirt", "tank"]):
        target_blog_title = "shirts & tops"
    elif any(x in ptype_lower for x in ["jacket", "coat", "outerwear", "blazer"]):
        target_blog_title = "coats & jackets"
    elif any(x in ptype_lower for x in ["sweater", "cardigan", "knit", "pullover"]):
        target_blog_title = "cardigans & sweaters"
        
    # 2. Try matching the targeted title
    if target_blog_title:
        for blog in all_blogs:
            title_lower = blog.get("title", "").lower()
            # Avoid matching Announcements or system blogs
            if "announcements" in title_lower or "tips" in title_lower:
                continue
            if target_blog_title in title_lower:
                return blog
                
    # 3. Fallback to "Women's Clothing" if available
    for blog in all_blogs:
        title_lower = blog.get("title", "").lower()
        if "women's clothing" in title_lower:
            return blog
            
    # 4. Fallback to any blog that is not a system blog
    non_system_blogs = [
        b for b in all_blogs 
        if "announcements" not in b.get("title", "").lower() and "tips" not in b.get("title", "").lower()
    ]
    if non_system_blogs:
        return non_system_blogs[0]
        
    if all_blogs:
        return all_blogs[0]
        
    if dry_run:
        return {"id": 0, "title": "MOCK Fallback Blog (Dry Run)"}
        
    # Create blog if none exist
    r = _req("post", f"{BASE}/blogs.json",
             json={"blog": {"title": "Women's Clothing"}})
    r.raise_for_status()
    new_blog = r.json()["blog"]
    all_blogs.append(new_blog)
    return new_blog

def update_article_and_metafields_graphql(article_id: int, payload: dict, seo_title: str, meta_desc: str, redirect_path: str = None, redirect_target: str = None):
    graphql_url = f"{BASE}/graphql.json"
    
    # Map REST payload to GraphQL ArticleUpdateInput
    gql_article = {
        "id": f"gid://shopify/Article/{article_id}",
        "title": payload.get("title"),
        "author": payload.get("author"),
        "contentHtml": payload.get("body_html"),
        "summaryHtml": payload.get("summary_html"),
        "tags": payload.get("tags"),
        "handle": payload.get("handle"),
    }
    
    if "published" in payload:
        gql_article["published"] = payload["published"]
    
    if "image" in payload and payload["image"].get("src"):
        gql_article["image"] = {
            "src": payload["image"]["src"],
            "altText": payload["image"]["alt"]
        }

    owner_id = f"gid://shopify/Article/{article_id}"
    
    metafields = [
        {
            "ownerId": owner_id,
            "namespace": "global",
            "key": "title_tag",
            "type": "single_line_text_field",
            "value": seo_title
        },
        {
            "ownerId": owner_id,
            "namespace": "global",
            "key": "description_tag",
            "type": "single_line_text_field",
            "value": meta_desc
        }
    ]

    variables = {
        "article": gql_article,
        "metafields": metafields
    }

    query = """
    mutation updateArticleAndMetafields($article: ArticleInput!, $metafields: [MetafieldsSetInput!]!
    """
    
    if redirect_path and redirect_target:
        query += ", $redirect: UrlRedirectInput!"
        variables["redirect"] = {
            "path": redirect_path,
            "target": redirect_target
        }

    query += """) {
      articleUpdate(input: $article) {
        article {
          id
          handle
        }
        userErrors {
          field
          message
        }
      }
      metafieldsSet(metafields: $metafields) {
        metafields {
          id
        }
        userErrors {
          field
          message
        }
      }
    """

    if redirect_path and redirect_target:
        query += """
      urlRedirectCreate(urlRedirect: $redirect) {
        urlRedirect {
          id
        }
        userErrors {
          field
          message
        }
      }
        """
        
    query += "}"

    r = _req("post", graphql_url, json={"query": query, "variables": variables})
    r.raise_for_status()
    data = r.json()
    
    if "errors" in data:
        raise RuntimeError(f"GraphQL Errors: {data['errors']}")
        
    update_errors = data.get("data", {}).get("articleUpdate", {}).get("userErrors", [])
    if update_errors:
        raise RuntimeError(f"Article Update Errors: {update_errors}")
        
    mf_errors = data.get("data", {}).get("metafieldsSet", {}).get("userErrors", [])
    if mf_errors:
        print(f"    [WARN] Metafields Set Errors: {mf_errors}")
        
    if redirect_path and redirect_target:
        redir_errors = data.get("data", {}).get("urlRedirectCreate", {}).get("userErrors", [])
        if redir_errors:
            print(f"    [INFO] Redirect Creation Message: {redir_errors[0].get('message')}")
        else:
            print(f"    [Redirect] Created redirect: '{redirect_path}' -> '{redirect_target}'")
            
    return data.get("data", {}).get("articleUpdate", {}).get("article")


# ── New functions for this script ──────────────────────────────────────────────
def fetch_all_products_with_images() -> list:
    """Fetch all products that have at least one image."""
    products, page_info = [], None
    while True:
        params = {
            "limit": 250,
            "fields": "id,title,handle,product_type,variants,images,vendor",
        }
        if page_info:
            params["page_info"] = page_info
        r = _req("get", f"{BASE}/products.json", params=params)
        r.raise_for_status()
        batch = r.json().get("products", [])
        products.extend([p for p in batch if p.get("images")]) # Only add products with images
        link = r.headers.get("Link", "")
        m = re.search(r'<[^>]*page_info=([^&>]+)[^>]*>;\s*rel="next"', link)
        if m:
            page_info = m.group(1)
        else:
            break
    return products

def fetch_all_articles_with_blog_info(article_id: int | None = None) -> list:
    """
    Fetches all articles from all blogs, attaching blog_id and blog_handle.
    If article_id is provided, fetches only that specific article.
    """
    all_blogs = get_all_blogs()
    all_articles = []

    for blog in all_blogs:
        blog_id = blog["id"]
        blog_handle = blog["handle"]
        
        if article_id:
            # Fetch specific article
            try:
                r = _req("get", f"{BASE}/blogs/{blog_id}/articles/{article_id}.json")
                r.raise_for_status()
                article = r.json().get("article")
                if article:
                    article["_blog_id"] = blog_id
                    article["_blog_handle"] = blog_handle
                    all_articles.append(article)
                    return all_articles # Found the article, return it
            except requests.exceptions.HTTPError as e:
                if e.response.status_code == 404:
                    continue # Article not in this blog, try next
                raise
        else:
            # Fetch all articles for this blog
            page_info = None
            while True:
                params = {"limit": 250, "fields": "id,title,handle,body_html,image,tags,summary_html,published_at,author"}
                if page_info:
                    params["page_info"] = page_info
                r = _req("get", f"{BASE}/blogs/{blog_id}/articles.json", params=params)
                r.raise_for_status()
                batch = r.json().get("articles", [])
                if not batch:
                    break
                for article in batch:
                    article["_blog_id"] = blog_id
                    article["_blog_handle"] = blog_handle
                    all_articles.append(article)
                link = r.headers.get("Link", "")
                m = re.search(r'<[^>]*page_info=([^&>]+)[^>]*>;\s*rel="next"', link)
                if m:
                    page_info = m.group(1)
                else:
                    break
    return all_articles


def regenerate_single_article(
    original_article: dict,
    all_products_with_images: list,
    all_blogs: list,
    dry_run: bool,
    force_format: str | None,
    type_map: dict,
    research_cache: dict,
    link_map: object
) -> dict:
    """
    Regenerates content for a single article, handles redirects, and updates Shopify.
    Returns a dictionary with status and details.
    """
    blog_id = original_article["_blog_id"]
    blog_handle = original_article["_blog_handle"]
    article_id = original_article["id"]
    original_title = original_article["title"]
    original_handle = original_article["handle"]
    original_tags = original_article.get("tags", "")
    
    log_entry = {
        "article_id": article_id,
        "original_title": original_title,
        "original_handle": original_handle,
        "status": "skipped",
        "changes": []
    }

    print(f"\nProcessing article: '{original_title}' (ID: {article_id}, Handle: {original_handle})")

    # 1. Select a relevant product for the article
    product_pool_for_selection = [p for p in all_products_with_images if p.get("images")]
    if not product_pool_for_selection:
        print("  [ERROR] No products with images available for selection. Skipping article.")
        log_entry["status"] = "error"
        log_entry["message"] = "No products with images for regeneration"
        return log_entry

    selected_product = None
    for ptype_keyword in ["jean", "dress", "skirt", "top", "pant", "jacket", "coat", "sweater", "cardigan", "swimwear", "activewear", "accessory"]:
        if ptype_keyword in original_title.lower():
            matching_products_for_selection = [p for p in product_pool_for_selection if ptype_keyword in (p.get("product_type") or "").lower()]
            if matching_products_for_selection:
                selected_product = random.choice(matching_products_for_selection)
                break
    
    if not selected_product:
        selected_product = random.choice(product_pool_for_selection)

    print(f"  Selected product for regeneration: '{selected_product['title']}' (Type: {selected_product.get('product_type')})")

    # 2. Generate content using the unified engine from weekly_trend_blog.py
    content_assets = generate_single_article_content(
        main_product=selected_product,
        all_products_with_images=all_products_with_images,
        link_map=link_map,
        type_map=type_map,
        research_cache=research_cache,
        force_format=force_format,
        dry_run=dry_run,
        original_handle_hint=original_handle
    )

    if not content_assets:
        print("  [ERROR] Content generation failed. Skipping article.")
        log_entry["status"] = "error"
        log_entry["message"] = "Content generation via weekly_trend_blog engine failed"
        return log_entry

    # 3. Unpack the generated assets
    html_body = content_assets["html_body"]
    new_title = content_assets["seo_title"]
    meta_desc = content_assets["meta_desc"]
    suggested_handle = content_assets["suggested_handle"]
    new_tags = content_assets["tags"]
    img_url = content_assets["img_url"]
    img_alt = content_assets["img_alt"]
    author = content_assets["author"]

    # 4. Merge tags
    original_tags_list = [t.strip() for t in original_tags.split(',') if t.strip()]
    final_tags = list(dict.fromkeys(new_tags + original_tags_list))[:25]

    # 5. Handle comparison and redirect
    final_handle = original_handle
    redirect_path = None
    redirect_target = None
    if suggested_handle != original_handle:
        # Check if handles are substantially different to avoid minor punctuation/word changes
        if suggested_handle.replace('-', '') not in original_handle.replace('-', '') and original_handle.replace('-', '') not in suggested_handle.replace('-', ''):
            print(f"  [HANDLE CHANGE] Suggested handle '{suggested_handle}' differs from original '{original_handle}'.")
            old_full_url = f"{STORE_URL}/blogs/{blog_handle}/{original_handle}"
            new_full_url = f"{STORE_URL}/blogs/{blog_handle}/{suggested_handle}" 
            if not dry_run:
                redirect_path = urlparse(old_full_url).path
                redirect_target = new_full_url
                final_handle = suggested_handle
                log_entry["changes"].append({"field": "handle", "old": original_handle, "new": suggested_handle, "redirect_created": True})
            else:
                print(f"    [DRY-RUN] Would change handle to '{suggested_handle}' and create redirect from '{old_full_url}' to '{new_full_url}'.")
                final_handle = suggested_handle # For dry-run output
                log_entry["changes"].append({"field": "handle", "old": original_handle, "new": suggested_handle, "redirect_created": True, "dry_run": True})
        else:
            print(f"  [HANDLE] Handle differs slightly, but keeping original handle: '{original_handle}' to preserve SEO.")
    else:
        print(f"  [HANDLE] Handle remains unchanged: '{original_handle}'.")

    # 6. Prepare payload for article update
    payload = {
        "title": new_title,
        "author": author,
        "body_html": html_body,
        "summary_html": meta_desc,
        "tags": ", ".join(final_tags),
        "handle": final_handle,
        "published": original_article.get("published_at") is not None,
    }
    if img_url:
        payload["image"] = {
            "src": img_url,
            "alt": img_alt,
        }
    
    if new_title != original_title:
        log_entry["changes"].append({"field": "title", "old": original_title, "new": new_title})
    if original_article.get("body_html") != html_body:
        log_entry["changes"].append({"field": "body_html", "old_len": len(original_article.get("body_html", "")), "new_len": len(html_body)})
    if original_article.get("image", {}).get("src") != img_url:
        log_entry["changes"].append({"field": "image_src", "old": original_article.get("image", {}).get("src"), "new": img_url})
    if original_article.get("image", {}).get("alt") != img_alt:
        log_entry["changes"].append({"field": "image_alt", "old": original_article.get("image", {}).get("alt"), "new": img_alt})
    if original_article.get("tags") != payload["tags"]:
        log_entry["changes"].append({"field": "tags", "old": original_tags, "new": payload["tags"]})
    if original_article.get("author") != payload["author"]:
        log_entry["changes"].append({"field": "author", "old": original_article.get("author"), "new": payload["author"]})

    # 7. Perform update
    if dry_run:
        print(f"  [DRY-RUN] Would update article {article_id} with new content and metadata.")
        print(f"    New Title: {new_title}")
        print(f"    New Handle: {final_handle}")
        print(f"    New Image: {img_url}")
        print(f"    New Tags: {', '.join(final_tags)}")
        log_entry["status"] = "dry_run_success"
    else:
        try:
            # Save a backup of the original article content before we edit it
            backup_data = {
                "article_id": article_id,
                "title": original_title,
                "handle": original_handle,
                "body_html": original_article.get("body_html", ""),
                "summary_html": original_article.get("summary_html", ""),
                "tags": original_tags,
                "image": original_article.get("image", {}),
                "author": original_article.get("author", ""),
                "published_at": original_article.get("published_at", ""),
                "backup_timestamp": datetime.now().isoformat()
            }
            backup_dir = REPO_ROOT / "backup_articles"
            backup_dir.mkdir(exist_ok=True)
            backup_file = backup_dir / f"article_{article_id}_{int(time.time())}.json"
            backup_file.write_text(json.dumps(backup_data, indent=2, ensure_ascii=False), encoding="utf-8")
            print(f"    [Backup] Saved original article content to backup_articles/{backup_file.name}")

            updated_article = update_article_and_metafields_graphql(article_id, payload, new_title, meta_desc, redirect_path, redirect_target)
            if updated_article:
                print(f"  ✓ Successfully updated article {article_id} and SEO metafields in one GraphQL call.")
                log_entry["status"] = "success"
            else:
                raise RuntimeError("Shopify update returned no article data.")
        except Exception as e:
            print(f"  [ERROR] Failed to update article {article_id}: {e}")
            log_entry["status"] = "error"
            log_entry["message"] = str(e)
            
    return log_entry

def main():
    parser = argparse.ArgumentParser(description="Regenerate content for existing Shopify blog articles.")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing to Shopify.")
    parser.add_argument("--force", action="store_true", help="Process ALL existing articles.")
    parser.add_argument("--article-id", type=int, default=None, help="Process a single specific article by ID.")
    parser.add_argument("--batch-size", type=int, default=20, help="Number of articles to process per batch in --force mode.")
    parser.add_argument("--batch-index", type=int, default=0, help="0-based index of the batch to process in --force mode.")
    parser.add_argument("--count-only", action="store_true", help="Print total number of articles to process and exit (for CI matrix).")
    parser.add_argument("--force-format", type=str, default=None,
                        choices=[m["id"] for m in wtb.ARTICLE_MODES],
                        help="Force a specific blog format for all regenerated articles.")
    args = parser.parse_args()

    if args.count_only:
        all_articles = fetch_all_articles_with_blog_info(args.article_id)
        print(len(all_articles))
        return

    print(f"\n{'='*70}")
    print(f"  MeeeShop Article Regenerator — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"  Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    print(f"  Scope: {'ALL articles' if args.force else (f'Article ID: {args.article_id}' if args.article_id else 'Default (not implemented yet)')}")
    if args.force:
        print(f"  Batch: {args.batch_index} of size {args.batch_size}")
    if args.force_format:
        print(f"  Forced Format: {args.force_format}")
    print(f"{'='*70}\n")

    store_info = wtb.fetch_store_product_types()
    type_map = store_info["types"]
    all_products = store_info["all_products"]
    all_products_with_images = [p for p in all_products if p.get("images")]

    if not all_products_with_images:
        sys.exit("ERROR: No products with images found in Shopify. Cannot regenerate articles.")
    print(f"Loaded {len(all_products_with_images)} products with images for content generation.")

    link_map = wtb.build_linker_map()
    research_cache = {}

    all_articles = fetch_all_articles_with_blog_info(args.article_id)
    if not all_articles:
        sys.exit("ERROR: No articles found to process.")

    articles_to_process = []
    if args.article_id:
        articles_to_process = [a for a in all_articles if a["id"] == args.article_id]
        if not articles_to_process:
            sys.exit(f"ERROR: Article with ID {args.article_id} not found.")
    elif args.force:
        start_index = args.batch_index * args.batch_size
        end_index = start_index + args.batch_size
        articles_to_process = all_articles[start_index:end_index]
        print(f"Processing batch {args.batch_index}: articles {start_index} to {end_index-1} out of {len(all_articles)} total.")
    else:
        sys.exit("ERROR: Please specify --force to process all articles or --article-id to process a single article.")

    if not articles_to_process:
        print("No articles selected for processing in this run.")
        return

    results = []
    all_blogs = get_all_blogs()
    for article in articles_to_process:
        result = regenerate_single_article(article, all_products_with_images, all_blogs, args.dry_run, args.force_format, type_map, research_cache, link_map)
        results.append(result)
        time.sleep(2) # Be kind to APIs

    print(f"\n{'='*70}")
    print("Regeneration Summary:")
    print(f"Total articles attempted: {len(results)}")
    print(f"Successful: {sum(1 for r in results if r['status'] == 'success' or r['status'] == 'dry_run_success')}")
    print(f"Errors: {sum(1 for r in results if r['status'] == 'error')}")
    print(f"{'='*70}\n")

    log_filename = f"regenerate_articles_log_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(LOG_DIR / log_filename, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    print(f"Detailed log saved to {LOG_DIR / log_filename}")

if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    main()