# utils.py – Helper utilities for trend_article_engine

"""
Utility module providing:
- download_article_content(url): fetches a webpage and extracts main article text.
- extract_keywords(text): simple keyword extraction yielding long‑tail and zero‑search terms.
- generate_collage(product_images): builds a premium‑style collage (2×2 or 3×3) from image bytes.
- upload_collage_to_shopify(handle, image_bytes): uploads collage to Shopify Files API and returns public URL.
"""

import base64
import re
import random
from io import BytesIO
from typing import List, Dict

import requests
import trafilatura
from bs4 import BeautifulSoup
from PIL import Image, ImageOps

# ---------------------------------------------------------------------------
# Configuration – these will be populated from the environment via the main script
# ---------------------------------------------------------------------------
from secrets_manager import get_secret

SHOP = get_secret("SHOPIFY_STORE")
TOKEN = get_secret("SHOPIFY_ACCESS_TOKEN")
API_VER = "2024-10"
BASE = f"https://{SHOP}/admin/api/{API_VER}"
HEADERS = {"X-Shopify-Access-Token": TOKEN, "Content-Type": "application/json"}

# ---------------------------------------------------------------------------
# 1. Article content download
# ---------------------------------------------------------------------------
def download_article_content(url: str) -> str:
    """Fetch a URL and return cleaned article text.

    Uses trafilatura as the primary scraper for high-quality boilerplate removal,
    falling back to BeautifulSoup if needed.
    """
    try:
        # 1. Try fetching with trafilatura
        downloaded = trafilatura.fetch_url(url, timeout=5)
        if downloaded:
            extracted = trafilatura.extract(downloaded, no_fallback=False, include_comments=False, include_tables=True)
            if extracted:
                # Clean whitespace
                text = re.sub(r"\s+", " ", extracted).strip()
                if len(text) > 100:
                    return text

        # 2. Fallback to requests + BeautifulSoup
        resp = requests.get(url, timeout=5, headers={"User-Agent": "Mozilla/5.0 (compatible; MeeeShop SEO bot/1.0)"})
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")
        article = soup.find("article")
        if article:
            text = article.get_text(separator=" ", strip=True)
        else:
            # Fallback – grab visible text from <p> elements
            paragraphs = soup.find_all("p")
            text = " ".join(p.get_text(strip=True) for p in paragraphs)
        # Clean whitespace
        text = re.sub(r"\s+", " ", text).strip()
        return text
    except Exception as e:
        print(f"[download_article_content] Failed for {url}: {e}")
        return ""


# ---------------------------------------------------------------------------
# 2. Keyword extraction (very lightweight, industry‑standard style)
# ---------------------------------------------------------------------------
def _phrase_frequencies(text: str, min_len: int = 3, max_len: int = 5) -> Dict[str, int]:
    """Return a dict mapping word‑phrase → count.

    Phrases are generated by sliding a window over the token list. The function is
    deliberately simple – it works well as a baseline for long‑tail detection.
    """
    tokens = [t.lower() for t in re.findall(r"\b\w+\b", text)]
    freqs: Dict[str, int] = {}
    for size in range(min_len, max_len + 1):
        for i in range(len(tokens) - size + 1):
            phrase = " ".join(tokens[i : i + size])
            freqs[phrase] = freqs.get(phrase, 0) + 1
    return freqs


def extract_keywords(text: str) -> Dict[str, List[str]]:
    """Extract simple long‑tail and zero‑search keywords.

    * **Long‑tail** – phrases that appear 2‑4 times in the article (rare enough
      to be valuable but still present).
    * **Zero‑search** – phrases that appear exactly once.
    """
    freqs = _phrase_frequencies(text)
    long_tail = [p for p, c in freqs.items() if 2 <= c <= 4]
    zero_search = [p for p, c in freqs.items() if c == 1]
    # Limit size for practicality
    long_tail = random.sample(long_tail, min(10, len(long_tail)))
    zero_search = random.sample(zero_search, min(10, len(zero_search)))
    return {"long_tail": long_tail, "zero_search": zero_search}


def extract_handle_count(text: str) -> int:
    """Extract item/outfit count from handle, title, or string (e.g., '5-stunning-outfits' -> 5). Default is 3."""
    if not text:
        return 3
    m = re.search(r'\b(\d+)\b', str(text))
    if m:
        num = int(m.group(1))
        if 2 <= num <= 10:
            return num
    return 3


def get_current_year() -> str:
    """Returns current system year dynamically (e.g., '2026' in 2026, '2027' in 2027)."""
    return str(datetime.now().year)


def enforce_current_year(text: str, target_year: str = None) -> str:
    """Sanitize text to replace any accidental past years with the dynamic current year."""
    if not text:
        return text
    if target_year is None:
        target_year = get_current_year()
    try:
        current_yr = int(target_year)
        past_years = [str(y) for y in range(2020, current_yr)]
        if not past_years:
            return text
        pattern = r'\b(' + '|'.join(past_years) + r')\b'
        return re.sub(pattern, str(target_year), str(text))
    except (ValueError, TypeError):
        return text


def is_product_compatible(main_product: dict, candidate: dict, topic_context: str = "") -> bool:
    """Check if candidate product is style-compatible and category-relevant to main_product & article topic."""
    main_id = main_product.get("id")
    cand_id = candidate.get("id")
    if main_id and cand_id and main_id == cand_id:
        return False
    if main_product.get("handle") and candidate.get("handle") and main_product.get("handle") == candidate.get("handle"):
        return False

    main_type = (main_product.get("product_type") or "").lower()
    main_title = (main_product.get("title") or "").lower()
    main_tags = (main_product.get("tags") or "").lower() if isinstance(main_product.get("tags"), str) else " ".join(main_product.get("tags") or []).lower()
    main_text = f"{main_type} {main_title} {main_tags}"

    cand_type = (candidate.get("product_type") or "").lower()
    cand_title = (candidate.get("title") or "").lower()
    cand_tags = (candidate.get("tags") or "").lower() if isinstance(candidate.get("tags"), str) else " ".join(candidate.get("tags") or []).lower()
    cand_text = f"{cand_type} {cand_title} {cand_tags}"

    topic_lower = (topic_context or "").lower()

    DENIM_KEYWORDS = ["jean", "denim", "jort"]
    ONE_PIECE_KEYWORDS = ["dress", "jumpsuit", "romper"]
    BOTTOM_KEYWORDS = ["jean", "denim", "pant", "skirt", "short", "legging", "skort", "trouser", "jort"]
    TOP_KEYWORDS = ["top", "blouse", "shirt", "tee", "t-shirt", "tank", "sweater", "cardigan", "knit", "pullover", "tunic"]
    OUTERWEAR_KEYWORDS = ["jacket", "coat", "blazer", "vest", "outerwear"]

    main_is_denim = any(kw in main_text for kw in DENIM_KEYWORDS) or any(kw in topic_lower for kw in DENIM_KEYWORDS)
    main_is_one_piece = any(kw in main_type or kw in main_title for kw in ONE_PIECE_KEYWORDS)
    main_is_bottom = any(kw in main_type or kw in main_title for kw in BOTTOM_KEYWORDS)
    main_is_top = any(kw in main_type or kw in main_title for kw in TOP_KEYWORDS)

    cand_is_one_piece = any(kw in cand_type or kw in cand_title for kw in ONE_PIECE_KEYWORDS)
    cand_is_bottom = any(kw in cand_type or kw in cand_title for kw in BOTTOM_KEYWORDS)
    cand_is_top = any(kw in cand_type or kw in cand_title for kw in TOP_KEYWORDS)
    cand_is_denim = any(kw in cand_text for kw in DENIM_KEYWORDS)

    is_care_guide = any(kw in topic_lower for kw in ["care", "wash", "maintenance", "stain", "odour", "laundry"])

    # 1. Denim topic/main: CANDIDATE CANNOT BE A DRESS / JUMPSUIT / ROMPER
    if main_is_denim and cand_is_one_piece:
        return False

    # 2. Bottoms cannot pair with other bottoms (e.g. Jeans + Shorts)
    if main_is_bottom and cand_is_bottom:
        return False

    # 3. One-pieces (Dresses) cannot pair with other one-pieces (e.g. Dress + Jumpsuit)
    if main_is_one_piece and cand_is_one_piece:
        return False

    # 4. Care Guide relevance
    if is_care_guide and main_is_denim:
        if not (cand_is_denim or cand_is_top or any(kw in cand_type or kw in cand_title for kw in OUTERWEAR_KEYWORDS)):
            return False

    return True


def _is_accessory_or_bag(product: dict) -> bool:
    """Return True if product is a bag, handbag, crossbody, purse, or accessory."""
    t = f"{(product.get('product_type') or '')} {(product.get('title') or '')}".lower()
    return any(kw in t for kw in ["bag", "crossbody", "handbag", "tote", "purse", "clutch", "wallet", "accessory"])


def select_styling_matches(main_product: dict, pool: list, num_matches: int = 2, topic_context: str = "") -> list[dict]:
    """Select styling match products from pool that are strictly compatible with main_product and topic_context.
    Guaranteed to return up to num_matches with category diversity (maximum 1 bag/accessory per article).
    """
    main_id = main_product.get("id")
    main_handle = main_product.get("handle", "")

    # Level 1: Strict topic and style compatibility
    compatible_pool = [
        p for p in pool
        if p.get("id") != main_id and p.get("handle") != main_handle and p.get("images")
        and is_product_compatible(main_product, p, topic_context)
    ]
    random.shuffle(compatible_pool)

    # Separate apparel items from bags/accessories to guarantee maximum 1 bag per article
    apparel_pool = [p for p in compatible_pool if not _is_accessory_or_bag(p)]
    accessory_pool = [p for p in compatible_pool if _is_accessory_or_bag(p)]

    selected = []

    # 1. Prefer at least 1-2 apparel pieces (tops, dresses, jackets, bottoms)
    if apparel_pool:
        take_apparel = min(len(apparel_pool), num_matches - (1 if accessory_pool and num_matches > 1 else 0))
        selected.extend(random.sample(apparel_pool, take_apparel))

    # 2. Add at most 1 bag/accessory if needed to complete num_matches
    if len(selected) < num_matches and accessory_pool:
        selected.append(random.choice(accessory_pool))

    # 3. If still need items, fill from remaining apparel
    remaining_apparel = [p for p in apparel_pool if p not in selected]
    while len(selected) < num_matches and remaining_apparel:
        item = random.choice(remaining_apparel)
        selected.append(item)
        remaining_apparel.remove(item)

    if len(selected) >= num_matches:
        return selected[:num_matches]

    # Level 2: Relaxed pool fallback
    relaxed_pool = [
        p for p in pool
        if p.get("id") != main_id and p.get("handle") != main_handle and p.get("images")
        and p not in selected
    ]
    random.shuffle(relaxed_pool)
    while len(selected) < num_matches and relaxed_pool:
        p = relaxed_pool.pop()
        if _is_accessory_or_bag(p) and any(_is_accessory_or_bag(x) for x in selected):
            continue  # Don't add a 2nd bag
        selected.append(p)

    return selected[:num_matches]


def get_category_style_phrase(product: dict) -> str:
    """
    Derives a clean, generic, plural category or style phrase from a product title and type.
    Ensures blog titles cover generic product categories/styles rather than hyper-specific vendor product titles.
    Examples:
      'Across the Way Woven Lace Mini Dress' -> 'Woven Lace Mini Dresses'
      'Judy Blue High Waist Straight Leg Jean' -> 'High-Waist Straight-Leg Jeans'
      'Emory Park Aeliana Top' -> 'Women's Tops & Blouses'
    """
    title = (product.get("title") or "").strip()
    ptype = (product.get("product_type") or "").strip().lower()
    t_lower = title.lower()

    # Clean vendor or brand prefix from title if present
    vendor = (product.get("vendor") or "").strip().lower()
    clean_title = t_lower
    if vendor and clean_title.startswith(vendor):
        clean_title = clean_title[len(vendor):].strip()

    # Subcategory / Style pattern matches (specific to general)
    subcategories = [
        ("lace mini dress", "Lace Mini Dresses"),
        ("lace maxi dress", "Lace Maxi Dresses"),
        ("woven lace", "Woven Lace Dresses"),
        ("woven dress", "Woven Dresses"),
        ("maxi dress", "Maxi Dresses"),
        ("midi dress", "Midi Dresses"),
        ("mini dress", "Mini Dresses"),
        ("casual dress", "Casual Dresses"),
        ("cocktail dress", "Cocktail Dresses"),
        ("wrap dress", "Wrap Dresses"),
        ("sweater dress", "Sweater Dresses"),
        ("shirt dress", "Shirt Dresses"),
        ("slip dress", "Slip Dresses"),
        ("flare jean", "Flare Jeans"),
        ("flare jeans", "Flare Jeans"),
        ("wide leg jean", "Wide-Leg Jeans"),
        ("wide leg jeans", "Wide-Leg Jeans"),
        ("straight leg jean", "Straight-Leg Jeans"),
        ("straight leg jeans", "Straight-Leg Jeans"),
        ("skinny jean", "Skinny Jeans"),
        ("skinny jeans", "Skinny Jeans"),
        ("bootcut jean", "Bootcut Jeans"),
        ("high waist jean", "High-Waist Jeans"),
        ("high waist", "High-Waist Denim"),
        ("denim jacket", "Denim Jackets"),
        ("denim skirt", "Denim Skirts"),
        ("linen top", "Linen Tops"),
        ("knit top", "Knit Tops"),
        ("crop top", "Crop Tops"),
        ("tank top", "Tank Tops"),
        ("graphic tee", "Graphic Tees"),
        ("t-shirt", "T-Shirts & Tees"),
        ("tee", "T-Shirts & Tees"),
        ("cardigan", "Cardigans & Sweaters"),
        ("pullover", "Sweaters & Knits"),
        ("sweater", "Sweaters & Knits"),
        ("blouse", "Women's Blouses & Tops"),
        ("skirt", "Women's Skirts"),
        ("skort", "Shorts & Skorts"),
        ("short", "Shorts & Skorts"),
        ("jort", "Shorts & Jorts"),
        ("pant", "Women's Pants & Trousers"),
        ("trouser", "Women's Pants & Trousers"),
        ("legging", "Women's Pants & Leggings"),
        ("jacket", "Women's Jackets & Blazers"),
        ("coat", "Women's Coats & Outerwear"),
        ("blazer", "Women's Blazers"),
        ("handbag", "Handbags & Bags"),
        ("tote", "Tote Bags & Handbags"),
        ("bag", "Handbags & Accessories"),
    ]

    for sub_kw, label in subcategories:
        if sub_kw in clean_title:
            return label

    # Category fallback
    if "jean" in ptype or "denim" in ptype or "jean" in t_lower or "denim" in t_lower:
        return "Women's Jeans"
    if "dress" in ptype or "dress" in t_lower:
        return "Women's Dresses"
    if any(x in ptype or x in t_lower for x in ["top", "blouse", "shirt", "tee"]):
        return "Women's Tops & Shirts"
    if any(x in ptype or x in t_lower for x in ["sweater", "cardigan", "knit"]):
        return "Women's Sweaters & Cardigans"
    if "skirt" in ptype or "skirt" in t_lower:
        return "Women's Skirts"
    if any(x in ptype or x in t_lower for x in ["pant", "trouser", "legging"]):
        return "Women's Pants & Trousers"
    if any(x in ptype or x in t_lower for x in ["jacket", "coat", "blazer", "outerwear"]):
        return "Women's Jackets & Outerwear"
    if any(x in ptype or x in t_lower for x in ["bag", "handbag", "accessory"]):
        return "Women's Handbags & Accessories"

    return "Women's Fashion Staples"


def sanitize_title_to_category_phrase(title: str, product: dict) -> str:
    """
    Guarantees that an article title NEVER contains a single vendor product name.
    If a specific vendor product title is detected inside title, converts it to the generic category/style phrase.
    """
    if not title or not product:
        return title or ""

    category_phrase = get_category_style_phrase(product)
    prod_title = (product.get("title") or "").strip()
    vendor = (product.get("vendor") or "").strip()

    clean_p = prod_title
    if vendor and clean_p.lower().startswith(vendor.lower()):
        clean_p = clean_p[len(vendor):].strip()

    # Remove trailing parenthesis or color details (e.g. '(medium wash)', '(red/blue)')
    clean_p_base = re.sub(r"\s*\([^)]+\)", "", clean_p).strip()

    if prod_title.lower() in title.lower():
        title = re.sub(re.escape(prod_title), category_phrase, title, flags=re.IGNORECASE)
    if clean_p and len(clean_p) > 3 and clean_p.lower() in title.lower():
        title = re.sub(re.escape(clean_p), category_phrase, title, flags=re.IGNORECASE)
    if clean_p_base and len(clean_p_base) > 3 and clean_p_base.lower() in title.lower():
        title = re.sub(re.escape(clean_p_base), category_phrase, title, flags=re.IGNORECASE)

    # Clean up double words or formatting leftover (e.g. 'Guide Guide', 'Women's Jeans Guide')
    title = re.sub(r"\b(\w+)\s+\1\b", r"\1", title, flags=re.IGNORECASE)
    return title.strip()

# ---------------------------------------------------------------------------
# 3. Collage generation — 1200x630 Discover landscape layout
# ---------------------------------------------------------------------------
def generate_collage(product_images: List[bytes], strip_height: int = 630) -> bytes:
    """Create a 1200x630 Google Discover eligible landscape 3-panel collage image.

    - Center image (product_images[0] - Featured product): TALLER (380x600 tile) with a solid white border.
    - Side images (Left & Right related products): SHORTER (360x500 tile), vertically centered.
    - Cream background (#f8f6f3).
    """
    if not product_images:
        raise ValueError("No product images provided for collage generation")

    CANVAS_W = 1200
    CANVAS_H = 630
    BG_COLOR = (248, 246, 243)     # cream background
    BORDER_COLOR = (255, 255, 255) # solid white border for featured image

    canvas = Image.new("RGB", (CANVAS_W, CANVAS_H), BG_COLOR)

    imgs = []
    for data in product_images:
        try:
            imgs.append(Image.open(BytesIO(data)).convert("RGB"))
        except Exception:
            pass

    if not imgs:
        raise ValueError("Could not decode any product images for the collage")

    feat_img = imgs[0]
    left_img = imgs[1] if len(imgs) > 1 else imgs[0]
    right_img = imgs[2] if len(imgs) > 2 else (imgs[1] if len(imgs) > 1 else imgs[0])

    # 1. Left image (Shorter - 360x500)
    fitted_left = ImageOps.fit(left_img, (360, 500), method=Image.Resampling.LANCZOS)
    canvas.paste(fitted_left, (20, (CANVAS_H - 500) // 2))

    # 2. Right image (Shorter - 360x500)
    fitted_right = ImageOps.fit(right_img, (360, 500), method=Image.Resampling.LANCZOS)
    canvas.paste(fitted_right, (820, (CANVAS_H - 500) // 2))

    # 3. Center featured image (TALLER - 380x600 with solid white border)
    inner_feat = ImageOps.fit(feat_img, (368, 588), method=Image.Resampling.LANCZOS)
    bordered_feat = ImageOps.expand(inner_feat, border=6, fill=BORDER_COLOR)
    canvas.paste(bordered_feat, (410, (CANVAS_H - 600) // 2))

    out_buf = BytesIO()
    canvas.save(out_buf, format="JPEG", quality=92, optimize=True)
    return out_buf.getvalue()

# ---------------------------------------------------------------------------
# 4. Upload collage to Shopify Files API
# ---------------------------------------------------------------------------
def upload_collage_to_shopify(handle: str, image_bytes: bytes) -> str:
    """Upload a collage image to Shopify Files API and return the public URL.

    The function creates a temporary file via the Files endpoint. The returned
    ``src`` field is a CDN URL that can be used as the article's featured image.
    """
    if not TOKEN:
        raise RuntimeError("SHOPIFY_ACCESS_TOKEN not set – cannot upload collage")

    b64_content = base64.b64encode(image_bytes).decode("utf-8")
    payload = {
        "file": {
            "attachment": b64_content,
            "filename": f"collage_{handle}.jpg",
            "alt": f"Featured collage for {handle}",
            "mime_type": "image/jpeg",
        }
    }
    url = f"{BASE}/files.json"
    resp = requests.post(url, json=payload, headers=HEADERS, timeout=20)
    resp.raise_for_status()
    data = resp.json()
    # The API returns a list under "files"
    file_info = data.get("files", [{}])[0]
    return file_info.get("public_url") or file_info.get("src") or ""

# End of utils.py
