# utils.py – Helper utilities for trend_article_engine

"""
Utility module providing:
- download_article_content(url): fetches a webpage and extracts main article text.
- extract_keywords(text): simple keyword extraction yielding long‑tail and zero‑search terms.
- generate_collage(product_images): builds a premium‑style collage (2×2 or 3×3) from image bytes.
- upload_collage_to_shopify(handle, image_bytes): uploads collage to Shopify Files API and returns public URL.
"""

import base64
import re
import random
from io import BytesIO
from typing import List, Dict

import requests
from bs4 import BeautifulSoup
from PIL import Image, ImageDraw, ImageFilter

# ---------------------------------------------------------------------------
# Configuration – these will be populated from the environment via the main script
# ---------------------------------------------------------------------------
from secrets_manager import get_secret

SHOP = get_secret("SHOPIFY_STORE")
TOKEN = get_secret("SHOPIFY_ACCESS_TOKEN")
API_VER = "2024-10"
BASE = f"https://{SHOP}/admin/api/{API_VER}"
HEADERS = {"X-Shopify-Access-Token": TOKEN, "Content-Type": "application/json"}

# ---------------------------------------------------------------------------
# 1. Article content download
# ---------------------------------------------------------------------------
def download_article_content(url: str) -> str:
    """Fetch a URL and return cleaned article text.

    The function attempts to locate a <article> tag; if not found it falls back to
    extracting the main body text. HTML tags are stripped and excessive whitespace
    is collapsed.
    """
    try:
        resp = requests.get(url, timeout=15, headers={"User-Agent": "Mozilla/5.0 (compatible; MeeeShop SEO bot/1.0)"})
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")
        article = soup.find("article")
        if article:
            text = article.get_text(separator=" ", strip=True)
        else:
            # Fallback – grab visible text from <p> elements
            paragraphs = soup.find_all("p")
            text = " ".join(p.get_text(strip=True) for p in paragraphs)
        # Clean whitespace
        text = re.sub(r"\s+", " ", text).strip()
        return text
    except Exception as e:
        print(f"[download_article_content] Failed for {url}: {e}")
        return ""

# ---------------------------------------------------------------------------
# 2. Keyword extraction (very lightweight, industry‑standard style)
# ---------------------------------------------------------------------------
def _phrase_frequencies(text: str, min_len: int = 3, max_len: int = 5) -> Dict[str, int]:
    """Return a dict mapping word‑phrase → count.

    Phrases are generated by sliding a window over the token list. The function is
    deliberately simple – it works well as a baseline for long‑tail detection.
    """
    tokens = [t.lower() for t in re.findall(r"\b\w+\b", text)]
    freqs: Dict[str, int] = {}
    for size in range(min_len, max_len + 1):
        for i in range(len(tokens) - size + 1):
            phrase = " ".join(tokens[i : i + size])
            freqs[phrase] = freqs.get(phrase, 0) + 1
    return freqs


def extract_keywords(text: str) -> Dict[str, List[str]]:
    """Extract simple long‑tail and zero‑search keywords.

    * **Long‑tail** – phrases that appear 2‑4 times in the article (rare enough
      to be valuable but still present).
    * **Zero‑search** – phrases that appear exactly once.
    """
    freqs = _phrase_frequencies(text)
    long_tail = [p for p, c in freqs.items() if 2 <= c <= 4]
    zero_search = [p for p, c in freqs.items() if c == 1]
    # Limit size for practicality
    long_tail = random.sample(long_tail, min(10, len(long_tail)))
    zero_search = random.sample(zero_search, min(10, len(zero_search)))
    return {"long_tail": long_tail, "zero_search": zero_search}

# ---------------------------------------------------------------------------
# 3. Collage generation (industry‑standard 2×2/3×3 grid with subtle glass‑morphism)
# ---------------------------------------------------------------------------
def generate_collage(product_images: List[bytes]) -> bytes:
    """Create a collage from a list of image bytes.

    The function:
    1. Resizes each image to a square (400 px) while maintaining aspect ratio.
    2. Arranges them in a grid – 2×2 if ≤4 images, otherwise 3×3.
    3. Applies a light blur + semi‑transparent overlay to achieve a premium
       glass‑morphism look.
    4. Returns the collage as JPEG bytes (< 2 MB).
    """
    if not product_images:
        raise ValueError("No product images provided for collage generation")

    # Determine grid size
    count = min(len(product_images), 9)  # cap at 9 for 3×3
    grid_dim = 2 if count <= 4 else 3
    thumb_size = 400

    # Prepare thumbnails
    thumbs = []
    for img_data in product_images[: count]:
        img = Image.open(BytesIO(img_data)).convert("RGB")
        img.thumbnail((thumb_size, thumb_size), Image.LANCZOS)
        # Pad to exact thumb size
        bg = Image.new("RGB", (thumb_size, thumb_size), (255, 255, 255))
        bg.paste(img, ((thumb_size - img.width) // 2, (thumb_size - img.height) // 2))
        thumbs.append(bg)

    # Create canvas
    collage_w = thumb_size * grid_dim
    collage_h = thumb_size * grid_dim
    collage = Image.new("RGB", (collage_w, collage_h), (245, 245, 245))

    for idx, thumb in enumerate(thumbs):
        row = idx // grid_dim
        col = idx % grid_dim
        collage.paste(thumb, (col * thumb_size, row * thumb_size))

    # Add subtle glass‑morphism overlay
    overlay = Image.new("RGBA", collage.size, (255, 255, 255, 30))
    collage = collage.convert("RGBA")
    collage = Image.alpha_composite(collage, overlay)
    collage = collage.filter(ImageFilter.GaussianBlur(radius=1))

    # Export to JPEG bytes
    out_buf = BytesIO()
    collage.convert("RGB").save(out_buf, format="JPEG", quality=85, optimize=True)
    return out_buf.getvalue()

# ---------------------------------------------------------------------------
# 4. Upload collage to Shopify Files API
# ---------------------------------------------------------------------------
def upload_collage_to_shopify(handle: str, image_bytes: bytes) -> str:
    """Upload a collage image to Shopify Files API and return the public URL.

    The function creates a temporary file via the Files endpoint. The returned
    ``src`` field is a CDN URL that can be used as the article's featured image.
    """
    if not TOKEN:
        raise RuntimeError("SHOPIFY_ACCESS_TOKEN not set – cannot upload collage")

    b64_content = base64.b64encode(image_bytes).decode("utf-8")
    payload = {
        "file": {
            "attachment": b64_content,
            "filename": f"collage_{handle}.jpg",
            "alt": f"Featured collage for {handle}",
            "mime_type": "image/jpeg",
        }
    }
    url = f"{BASE}/files.json"
    resp = requests.post(url, json=payload, headers=HEADERS, timeout=20)
    resp.raise_for_status()
    data = resp.json()
    # The API returns a list under "files"
    file_info = data.get("files", [{}])[0]
    return file_info.get("public_url") or file_info.get("src") or ""

# End of utils.py
