#!/usr/bin/env python3
"""
regenerate_articles.py — Regenerates content for existing Shopify blog articles
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This script fetches existing published blog articles from Shopify and regenerates
their content using the same AI-driven pipeline as `weekly_trend_blog.py` and
`blog_daily.py`. It ensures that the regenerated content aligns with Google
Discover and E-E-A-T standards, including fresh HTML, SEO metadata, and
featured image collages.

For each article:
  1. A relevant product and article format are selected from the store's catalog.
  2. New, Discover-ready HTML content is generated by AI.
  3. SEO metafields (title_tag, description_tag) are set.
  4. A featured image collage is created and uploaded.
  5. The article's handle (URL) is compared with a newly suggested handle.
  6. If the handle changes, a 301 redirect is created from the old URL to the new one.
  7. The article is updated on Shopify with the new content and metadata.

Usage:
  python scripts/regenerate_articles.py --dry-run        # Preview changes, no Shopify writes
  python scripts/regenerate_articles.py --force          # Regenerate ALL articles
  python scripts/regenerate_articles.py --article-id 123 # Regenerate one specific article
  python scripts/regenerate_articles.py --force --batch-size 20 --batch-index 0 # Batch processing
"""

import os, sys, re, time, random, json, argparse
from datetime import datetime
from pathlib import Path
from urllib.parse import quote, urlparse

import requests
from bs4 import BeautifulSoup
from PIL import Image
from io import BytesIO

# ── Path setup ─────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT   = SCRIPT_DIR.parent
LOG_DIR     = REPO_ROOT / "logs"
LOG_DIR.mkdir(exist_ok=True)

sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(REPO_ROOT))

import ai_client
from secrets_manager import inject_to_env, get_secret
inject_to_env()

# ── Shopify credentials ────────────────────────────────────────────────────────
SHOP    = get_secret("SHOPIFY_STORE")
TOKEN   = get_secret("SHOPIFY_ACCESS_TOKEN")
API_VER = "2024-10"
BASE    = f"https://{SHOP}/admin/api/{API_VER}"
HEADERS = {"X-Shopify-Access-Token": TOKEN, "Content-Type": "application/json"}
STORE_URL = get_secret("STORE_BASE_URL") or f"https://{SHOP}"

if not TOKEN:
    sys.exit("ERROR: SHOPIFY_ACCESS_TOKEN not set.")

YEAR  = datetime.now().year
MONTH = datetime.now().strftime("%B %Y")
TODAY = datetime.now().strftime("%Y-%m-%d")

# ── Reused from blog_daily.py / weekly_trend_blog.py ───────────────────────────
PEN_NAMES = [
    "Elena Vance, MeeeShop Lead Stylist",
    "Seraphina Croft, MeeeShop Fashion Editor",
    "Audrey Sterling, MeeeShop Style Director",
    "Maya Devereaux, MeeeShop Fashion Consultant",
    "Vivienne Vance, MeeeShop Senior Stylist",
    "Genevieve Thorne, MeeeShop Trend Forecaster"
]

EEAT_RULES = (
    "EDITORIAL VOICE & E-E-A-T REQUIREMENTS (non-negotiable — Google trust signals + reader value):\n\n"

    "═══ OPENING HOOK (Critical for Google Discover CTR) ═══\n"
    "Open with a SPECIFIC, OPINIONATED hook that immediately validates the reader's real-world problem.\n"
    "✅ GOOD: 'The single-roll cuff is everywhere right now — and after testing every variation on dark wash, barrel leg, and cigarette jeans, here is exactly what actually works.'\n"
    "✅ GOOD: 'If your jeans still smell faintly musty after washing, you are not alone — and a second wash is rarely the answer.'\n"
    "❌ BAD: 'Jeans are a timeless wardrobe staple that women everywhere love.'\n"
    "❌ BAD: 'In today's world of fashion, finding the perfect pair of jeans can be challenging.'\n\n"

    "═══ VOICE & TONE ═══\n"
    "Write as a knowledgeable, trusted stylist friend — warm, direct, and specific. NOT a brand.\n"
    "• Use second person ('your jeans', 'your body') to keep the reader central.\n"
    "• Mix short punchy sentences with longer explanatory ones. Vary rhythm deliberately.\n"
    "• Be opinionated where it helps: 'Skip the wide-leg for petite frames — the volume will overwhelm.'\n"
    "• Acknowledge real trade-offs: 'Cigarette jeans are incredibly chic, but if you run curvy in the hip, size up and have them tailored at the waist.'\n\n"

    "═══ SPECIFIC RECOMMENDATIONS (Required — not vague) ═══\n"
    "All styling advice MUST name specific item categories with descriptors. MeeeShop sells clothing only — do NOT recommend specific shoes. Instead recommend clothing layers, tops, bags, belts, and jewelry with specific descriptors:\n"
    "✅ GOOD: 'A relaxed linen button-down in ecru — untucked, one button undone at the collar — hits differently over dark wash jeans.'\n"
    "✅ GOOD: 'A structured mini tote in chocolate brown or off-white anchors the quiet luxury aesthetic without trying too hard.'\n"
    "✅ GOOD: 'Layer a cropped blazer in camel or ivory over the top — it balances the proportions instantly.'\n"
    "❌ BAD: 'Pair with heels for a polished look.' (no shoe recs — MeeeShop doesn't sell shoes)\n"
    "❌ BAD: 'Accessorize to complete the outfit.' (too vague)\n"
    "❌ BAD: 'Add a bag to elevate the look.' (generic filler)\n\n"

    "═══ 2026 TREND CONTEXT (Weave in naturally — sourced from Flipboard #Style 8.4M followers) ═══\n"
    "Reference real trends where relevant but do NOT force every trend into every article:\n"
    "• Quiet luxury: 'No logos, no distressing — clean dark wash denim with a tucked-in linen shirt is the 2026 quiet luxury formula.'\n"
    "• Cigarette/stovepipe silhouette replacing wide-leg as dominant denim cut in 2026.\n"
    "• Dark indigo clean wash over distressed/light wash — reads more expensive instantly.\n"
    "• Linen top + dark wash jean = the heat-proof chic summer formula trending on Flipboard.\n"
    "• All-black outfits even in summer — trending on Flipboard #Style with 8.4M followers.\n"
    "• Oversized blazer over a simple tank + straight-leg jeans = the office-to-evening formula.\n\n"

    "═══ STRUCTURE & FORMAT ═══\n"
    "• Use H2 for major sections, H3 for sub-steps or occasions.\n"
    "• Include at least 1 blockquote styled as a 'Stylist Tip' with specific advice.\n"
    "• Use bullet lists for step-by-step instructions (care guides, how-tos).\n"
    "• For outfit formulas: name EACH look with a creative occasion title (e.g., 'Look 1: Sunday Farmers Market', not 'Casual Look').\n"
    "• Vary structure between articles — avoid formulaic repetition.\n\n"

    "═══ BANNED PHRASES (never use these) ═══\n"
    "elevate your look | effortlessly chic | perfect for any occasion | versatile wardrobe staple\n"
    "timeless classic | fashion-forward | look and feel your best | style game\n"
    "take your look to the next level | complete your outfit | fashion journey\n\n"

    "═══ TRUST SIGNALS ═══\n"
    "Include naturally (once, in CTA or intro): Free US shipping on orders $50+. Easy 7-day returns. Sizes XS–3X.\n\n"
)

SEED_KEYWORDS = [
    # 2026 Trending — sourced from Flipboard #Style (8.4M followers) & Who What Wear
    "women's fashion 2026", "summer outfit ideas for women 2026",
    "affordable women's clothing USA", "summer dress outfits for women",
    "women's jeans styles guide", "casual chic outfits women",
    "women's fashion trends 2026", "cute outfits under $50",
    "stylish women's tops", "best dresses for women",
    "women's summer wardrobe essentials", "affordable boutique fashion USA",
    "women's outfit ideas", "how to style women's clothing",
    "plus size fashion tips", "work outfits for women",
    "women's weekend casual looks", "women's spring outfit ideas 2026",
    "best tops to wear with jeans", "how to build a capsule wardrobe women",
    "women's date night outfit ideas",
    "Zenana women's clothing basics guide", "how to style POL clothing bohemian pieces",
    "Emory Park boutique clothing outfits", "best Judy Blue jeans styles for women",
    "Risen stretch denim jeans review", "Umgee USA clothing styling ideas",
    "Hyfve clothing fashion trends", "Bibi clothing cute outfits",
    "Artemis Vintage denim styles",
    # Jeans-specific trending 2026 (Flipboard #Jeans 66K followers)
    "how to style jeans 2026", "dark wash jeans outfits",
    "quiet luxury jeans women", "cigarette jeans styling tips",
    "barrel leg jeans vs wide leg jeans", "blazer with jeans outfit ideas",
    "tops to wear with jeans 2026", "how to look taller in jeans",
    # Care & How-To (high search intent, Flipboard trending)
    "how to wash jeans without fading", "how to remove stains from jeans",
    "how to remove smell from clothes", "how to fix pilling on clothes",
    "jeans care guide 2026",
    # Summer 2026 (Flipboard #SummerFashion 73.9K followers)
    "linen top with jeans outfit", "summer denim outfit ideas 2026",
    "all black summer outfit women", "women's capsule wardrobe 2026",
    "linen dress summer 2026",
]

# High-intent blog formats
FORMATS = ["buying_guide", "comparison", "problem_solver", "trend_report", "outfit_formula", "care_guide", "sizing_guide"]

def _req(method: str, url: str, **kw):
    for attempt in range(5):
        try:
            r = getattr(requests, method)(url, headers=HEADERS, timeout=30, **kw)
            if r.status_code == 429:
                wait = int(float(r.headers.get("Retry-After", 4)))
                print(f"    [rate-limit] sleeping {wait}s…")
                time.sleep(wait)
                continue
            return r
        except requests.exceptions.ConnectionError:
            time.sleep(3 * (attempt + 1))
    raise RuntimeError(f"{method.upper()} {url} failed after 5 attempts")

def _slugify(text: str) -> str:
    """Convert a title/phrase to a URL-safe handle slug."""
    text = text.lower()
    text = re.sub(r"[''\"'']", "", text)
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")[:80]

def _lsi_keywords(ptype: str, keyword: str) -> list[str]:
    """Return LSI / secondary keywords relevant to this product type and primary keyword."""
    base_lsi = [
        "women's outfit ideas", "stylish women USA", "affordable fashion",
        "how to style", "women's clothing guide", "USA boutique fashion",
    ]
    ptype_lsi = {
        "dress":      ["summer dress outfits", "flattering dresses women", "dress styles guide",
                       "midi dress", "casual dress", "linen dresses 2026"],
        "jean":       ["jeans for women 2026", "best fitting jeans", "dark wash jeans outfits",
                       "high waist jeans", "women's denim guide", "cigarette jeans styling",
                       "quiet luxury denim", "barrel leg jeans", "linen top with jeans outfit",
                       "denim trends 2026"],
        "top":        ["tops for women", "blouse styles", "women's shirts", "work tops",
                       "casual tops women", "linen tops summer 2026"],
        "blouse":     ["blouse outfits", "women's blouse styles", "office blouse",
                       "flowy tops women", "summer blouse ideas"],
        "skirt":      ["skirt outfits women", "midi skirt", "mini skirt style",
                       "how to wear skirts", "asymmetric skirt 2026"],
        "pant":       ["women's pants guide", "trousers women", "wide leg pants",
                       "work pants women", "trouser trends 2026"],
        "jacket":     ["women's jacket outfits", "layering outfits", "blazer women",
                       "casual jacket", "blazer jeans combo 2026"],
        "coat":       ["women's coat styles", "winter coat", "trench coat women", "coat outfit ideas"],
        "sweater":    ["cozy sweater outfits", "women's knitwear", "sweater styles", "fall fashion women"],
        "cardigan":   ["cardigan outfits", "layering cardigan", "open front cardigan", "cozy fashion"],
        "swimwear":   ["swimsuit styles women", "bikini guide", "one piece swimsuit", "flattering swimwear"],
        "activewear": ["workout outfit women", "athleisure look", "gym clothes women", "active style"],
        "accessory":  ["women's accessories", "accessory guide", "how to accessorize", "fashion accessories"],
    }
    extras = []
    for k, v in ptype_lsi.items():
        if k in ptype:
            extras = v
            break
    combined = list(dict.fromkeys(extras + base_lsi))[:8]
    return combined

def _build_prompt(fmt: str, product: dict, keyword: str, title_hint: str, similar_products: list | None = None, matching_products: list | None = None) -> tuple[str, str]:
    display_name = get_product_display_name(product)
    clean_ptype = get_clean_product_type(product)
    price  = product["variants"][0]["price"] if product.get("variants") else "49"
    handle = product.get("handle", "")
    url    = f"{STORE_URL}/products/{handle}" if handle else STORE_URL

    lsi    = _lsi_keywords(clean_ptype, keyword)
    lsi_str = ", ".join(f'"{k}"' for k in lsi)

    if similar_products is None:
        similar_products = []
    if matching_products is None:
        matching_products = []

    # Build styling instructions for the collage items to tie image & text together
    match_instr = ""
    if matching_products:
        clean_matches = [get_product_display_name(m) for m in matching_products]
        matches_str = " and ".join([f"'{m_title}' (${m['variants'][0]['price'] if m.get('variants') else '49'})" for m_title, m in zip(clean_matches, matching_products)])
        match_instr = (
            f"- We are featuring a styling lookbook collage showing this product paired with: {matches_str}.\n"
            f"- In the styling or outfit sections of your article, you MUST explicitly mention these matching pieces by name, explaining how to style them together with the main featured product to create a complete, cohesive outfit (e.g., 'pair it with the {clean_matches[0]}' or 'complete this look using the {clean_matches[1]}').\n"
        )

    base = (
        f"You are a fashion editor at MeeeShop, a USA women's clothing boutique.\n"
        f"Write a {MONTH} blog post. Target keyword: '{keyword}'\n"
        f"Feature product: {display_name} — ${price}\n"
        f"Category: {clean_ptype}\n\n"
        f"{EEAT_RULES}"
        f"2026 TREND FRESHNESS — weave 1-2 of these angles in naturally where relevant:\n"
        f"  • Quiet luxury: clean lines, no logos, elevated basics — trending on Flipboard #Style (8.4M followers)\n"
        f"  • Cigarette/stovepipe jeans — the 2026 dominant denim silhouette replacing baggy styles\n"
        f"  • Dark indigo/clean wash denim — the 'elevated' denim choice over distressed styles\n"
        f"  • Linen tops + jeans = heat-proof, chic summer formula (layer untucked or half-tuck)\n"
        f"  • All-black outfits even in summer — 7-look styling trend (Flipboard #Style)\n"
        f"  • Oversized blazer over a simple tank + straight-leg jeans = the office-to-evening 2026 formula\n\n"
        f"SEO rules (follow precisely):\n"
        f"- Primary keyword '{keyword}': use 3-4 times naturally — once in H1, once in first paragraph, 1-2 times in body/conclusion\n"
        f"- LSI / secondary keywords to weave in naturally (don't force all, pick what fits): {lsi_str}\n"
        f"- At least 2 of these LSI keywords must appear in H2 subheadings\n"
        f"- Do NOT write or include any HTML links (<a> tags) to the product page or MeeeShop anywhere in the body text. The product card and shop-the-look widgets will be programmatically injected by the system, so manual linking inside the article is redundant and violates SEO guidelines by looking spammy.\n"
        f"- Limit mentions of the product title '{display_name}' to a maximum of 2 times in the entire body. When referring to the product subsequent times, use pronouns or the specific generic term '{clean_ptype}' (e.g., 'this {clean_ptype}', 'the {clean_ptype}', 'it', 'this piece') instead of repeating the full product name.\n"
        f"- H1 title must include year {YEAR} or 'for Women'\n"
        f"- Keyword density: natural reading, never stuffed — if it sounds forced, rephrase\n"
        f"- Answer a real problem women face when shopping for this item\n"
        f"{match_instr}"
        f"- To avoid programmatic footprints, vary your structure. Occasionally include a <blockquote style='border-left: 3px solid #ccc; padding-left: 10px; margin: 15px 0; font-style: italic;'> for a 'Stylist Tip', or a styled callout box. Make the flow feel like a hand-written editorial, not a template.\n"
        f"- You MUST include a Shoppers' Q&A section immediately before the final CTA/verdict section. This must consist of:\n"
        f"  <h2>Shoppers' Q&A: Common Questions Answered</h2>\n"
        f"  <h3>Why should the {display_name} be in my closet?</h3>\n"
        f"  <p>[Detailed first-person answer from a stylist explaining why it's a wardrobe staple, 40-50 words]</p>\n"
        f"  <h3>What is the fabric composition and how do I wash this style?</h3>\n"
        f"  <p>[Detailed answer detailing how to wash and maintain the fabric quality, 40-50 words]</p>\n"
        f"  <h3>How do I choose the correct size for the {display_name}?</h3>\n"
        f"  <p>[Actionable advice on sizing fit, body shape guidelines, sizes XS-3X, 40-50 words]</p>\n\n"
        f"Store info: Free US shipping on orders $50+. Easy 7-day returns. Sizes XS-3X.\n\n"
    )

    if fmt == "buying_guide":
        prompt = base + (
            f"Format: Definitive Buying Guide (Refinery29 / Who What Wear editorial depth)\n"
            f"Write in HTML (<h1>,<h2>,<h3>,<p>,<ul>,<li>):\n"
            f"1. <h1> '{title_hint}'\n"
            f"2. <p> Hook — open with a SPECIFIC observation or problem (NOT 'In today's fashion world...'). Example: 'Here is the honest truth about the {clean_ptype} question I get asked every single week.' (80 words, stylist voice)\n"
            f"3. <h2> What Actually Makes a Good {clean_ptype.title()}? (4 real criteria — e.g., fabric weight, drape quality, seam construction, size consistency — as <ul><li> with 1-sentence explanations. Be specific, not generic.)\n"
            f"4. <h2> Why {display_name} Made Our Edit: The Honest Breakdown (120 words — discuss actual cut, fabric drape, fit reality for different body shapes, price-to-quality ratio. Do NOT include HTML links.)\n"
            f"5. <h2> 3 Real-Life Outfit Recipes (H3 each with creative occasion name like 'The Power Lunch' or 'Saturday Gallery Hop'. Each: list specific tops with fabric+color, a layering piece like a blazer or cardigan, a bag style, and one accessory with the reason it works. Do NOT recommend shoes — MeeeShop sells clothing only. 70 words each.)\n"
            f"6. <h2> Who This Actually Works For (and Who Should Skip It) (60 words — honest body shape and lifestyle fit advice. Acknowledge trade-offs.)\n"
            f"7. <h2> Sizing: Buy Your Size or Size Up? (40 words — specific verdict on fit, note if runs small/large, bust and length reality for XS-3X)\n"
            f"8. <p> Direct, warm CTA: price, free US shipping on orders $50+, 7-day returns. Do NOT include HTML links.\n"
            f"Target: 800-950 words. Output ONLY clean HTML, no markdown code fences."
        )

    elif fmt == "comparison":
        real_alts = [
            p for p in similar_products
            if p.get('handle') != product.get('handle') and p.get('images')
        ][:2]
        if len(real_alts) < 2:
            # Fallback: any 2 other products
            real_alts = [
                p for p in similar_products
                if p.get('handle') != product.get('handle')
            ][:2]
        alt1_display = get_product_display_name(real_alts[0]) if real_alts else "a similar style"
        alt1_price = real_alts[0]['variants'][0]['price'] if (real_alts and real_alts[0].get('variants')) else "49"
        alt2_display = get_product_display_name(real_alts[1]) if len(real_alts) > 1 else "another option"
        alt2_price = real_alts[1]['variants'][0]['price'] if (len(real_alts) > 1 and real_alts[1].get('variants')) else "49"
        
        prompt = base + (
            f"Format: Comparison Article — helps women choose the right style\n"
            f"Write in HTML:\n"
            f"1. <h1> '{title_hint}'\n"
            f"2. <p> Intro — 'I get asked this question every week from our customers: how does {display_name} compare to other styles?' (70 words, empathetic stylist perspective)\n"
            f"3. <h2> Option 1: {display_name} — What I Love + Who It's For (100 words, detailed stylist analysis of the drape and cut, do NOT include HTML links)\n"
            f"4. <h2> Option 2: {alt1_display} — Pros, Cons, and Styling Fit (80 words). Price: ${alt1_price}\n"
            f"5. <h2> Option 3: {alt2_display} — Pros, Cons, and Styling Fit (80 words). Price: ${alt2_price}\n"
            f"6. <h2> Quick Styling Comparison (HTML table: Style | Best For | Price Range | Fabric Draping Winner)\n"
            f"7. <h2> My Honest Verdict — The Winner for Most Women (80 words, stylist recommendation)\n"
            f"8. <p> CTA to shop {display_name} at MeeeShop + price, free shipping on orders $50+, easy returns, do NOT include HTML links\n"
            f"Target: 750-900 words. Output ONLY clean HTML."
        )

    elif fmt == "problem_solver":
        problems = {
            "dress":      "finding a flattering dress that works for multiple occasions without breaking the budget",
            "jean":       "finding jeans that actually fit your body type perfectly",
            "top":        "building a versatile work-to-weekend wardrobe on a budget",
            "blouse":     "finding a blouse that's polished enough for work but fun enough for weekends",
            "pant":       "finding pants that look amazing and feel comfortable all day long",
            "skirt":      "styling a skirt confidently for every occasion without overthinking it",
            "sweater":    "staying stylish and warm without looking frumpy in the cold months",
            "cardigan":   "layering outfits that look intentional, not sloppy",
            "jacket":     "layering outfits without looking bulky or adding too much volume",
            "coat":       "finding a coat that's practical in the cold but still looks chic",
            "swimwear":   "finding a swimsuit that flatters your figure and makes you feel confident",
            "activewear": "finding workout clothes that look great enough to wear all day",
        }
        problem = next(
            (v for k, v in problems.items() if k in clean_ptype or k in display_name.lower()),
            "dressing well on a budget without sacrificing style or looking like everyone else",
        )
        prompt = base + (
            f"Format: Problem-Solver — directly addressing '{problem}'\n"
            f"Write in HTML:\n"
            f"1. <h1> '{title_hint}'\n"
            f"2. <p> Opening — validate the reader's exact pain point with empathy and insider knowledge. Start with their frustration, not a generic intro. (80 words, second-person, warm and direct — like a stylist friend who finally gets it)\n"
            f"3. <h2> Why It Keeps Happening (and It's Not Your Fault) (60 words — explain the real structural or industry reason behind the problem, e.g., sizing inconsistency across brands, fabric quality shortcuts, etc.)\n"
            f"4. <h2> The Fix: Why {display_name} Solves This (120 words — describe specific cut details, fabric stretch or structure, and exactly HOW these features solve '{problem}'. Do NOT include HTML links.)\n"
            f"5. <h2> 3 Outfit Recipes That Prove It (H3 each with creative occasion name. Each outfit: name specific shoes with material+color, top with silhouette+fabric, bag style, one accessory. 70 words each.)\n"
            f"6. <h2> 4 Stylist Rules That Change Everything (bullet list — SPECIFIC tips like 'Always size up one in {clean_ptype} if you are between sizes — the waistband gap is easier to tailor than a tight seat.')\n"
            f"7. <p> Honest, warm CTA: price of {display_name}, free US shipping on $50+, 7-day returns, sizes XS-3X. Do NOT include HTML links.\n"
            f"Target: 750-900 words. Output ONLY clean HTML."
        )

    elif fmt == "trend_report":
        prompt = base + (
            f"Format: {MONTH} Trend Report — grounded in real 2026 fashion data\n"
            f"Write in HTML:\n"
            f"1. <h1> '{title_hint}'\n"
            f"2. <p> Intro — Anchor the reader in what is actually happening in fashion RIGHT NOW in summer 2026. Reference real Flipboard/street-style trends (quiet luxury, cigarette jeans replacing wide-leg, wedge sandals + denim combo). Be specific about what changed. (70 words, confident stylist voice)\n"
            f"3. Five trends, each as <h2> with opinionated trend name + 90-word description:\n"
            f"   - Trend #1 MUST be {display_name} (do NOT include HTML links) — explain why it fits the 2026 moment\n"
            f"   - Trend #2: Cigarette/Stovepipe Jeans Taking Over — why the wide-leg silhouette is being replaced\n"
            f"   - Trend #3: The Quiet Luxury Denim Edit — dark indigo, no distressing, clean lines\n"
            f"   - Trend #4: Linen + Denim Summer Formula — the heat-proof styling answer\n"
            f"   - Trend #5: One more relevant {MONTH} 2026 micro-trend for US women shoppers\n"
            f"   - Each trend: what it is, why it is trending NOW, specific how-to-wear formula, who it suits and who should skip it\n"
            f"4. <h2> How to Mix Two Trends Without Looking Overdone (60 words — a practical 'choose one focal piece' rule)\n"
            f"5. <p> Direct CTA: shop {display_name} at MeeeShop, price, free shipping on $50+. Do NOT include HTML links.\n"
            f"Target: 800-950 words. Output ONLY clean HTML."
        )

    elif fmt == "care_guide":
        is_denim_care = any(x in clean_ptype for x in ["jean", "denim"])
        denim_care_specifics = (
            f"   DENIM-SPECIFIC RULES to cover (sourced from real denim care standards):\n"
            f"   • Wash only every 5-10 wears — overwashing breaks down denim fibers and fades color\n"
            f"   • ALWAYS wash inside out — protects the indigo surface dye\n"
            f"   • Cold water ONLY — hot water causes shrinking and fading\n"
            f"   • NO fabric softener — it breaks down stretch fibers in stretch denim\n"
            f"   • Skip the dryer — hang dry flat to preserve the fit and elasticity\n"
            f"   • Spot clean small stains with a damp cloth instead of a full wash\n"
            f"   • The freezer method for odor: seal in a zip bag, freeze overnight — kills odor-causing bacteria\n"
        ) if is_denim_care else ""
        prompt = base + (
            f"Format: Practical Fabric Care & Washing Guide (reader-first, actionable like a Refinery29 care article)\n"
            f"Write in HTML:\n"
            f"1. <h1> '{title_hint}'\n"
            f"2. <p> Hook — open with a SPECIFIC care mistake women make that ruins their {clean_ptype}. E.g., for denim: 'Washing your jeans after every wear is the fastest way to ruin them — and most women don\'t know it.' (70 words, direct, problem-first)\n"
            f"3. <h2> Reading Your Care Label: What Those Symbols Actually Mean (explain the 4 main care symbols: wash tub, triangle, square, iron — with plain English translations)\n"
            f"4. <h2> The Right Way to Wash {display_name}\n"
            f"   <h3> Machine Washing (temperature, cycle, detergent — be precise, e.g., 'cold/delicate cycle, liquid detergent, turn inside out')\n"
            f"   <h3> Hand Washing (when and how — water temp, gentle swirl, no wringing)\n"
            f"{denim_care_specifics}"
            f"5. <h2> Drying Without Damage (air dry vs dryer reality — explain WHY heat damages the fabric, give specific hang-dry instructions)\n"
            f"6. <h2> Storage Tips That Preserve the Fit (folding vs hanging for this garment type, how to avoid stretch marks and misshaping)\n"
            f"7. <blockquote style='border-left:3px solid #ccc;padding-left:10px;margin:15px 0;font-style:italic;'> A Stylist Tip with one specific care hack that most people don't know\n"
            f"8. <p> Warm CTA: shop the {display_name} at MeeeShop, price, free US shipping on $50+, 7-day returns. Do NOT include HTML links.\n"
            f"Target: 750-900 words. Output ONLY clean HTML."
        )

    elif fmt == "sizing_guide":
        prompt = base + (
            f"Format: Inclusive Sizing & Fit Guide (body-shape-positive, honest, actionable)\n"
            f"Write in HTML:\n"
            f"1. <h1> '{title_hint}'\n"
            f"2. <p> Hook — open with the real frustration: 'Ordering {clean_ptype} online is a gamble — until you know the three measurements that matter most.' (70 words, warm, second-person, direct)\n"
            f"3. <h2> How to Measure Yourself in 3 Steps (waist, hips, inseam/length — give specific instructions for each measurement point)\n"
            f"4. <h2> MeeeShop Size Chart: XS to 3X Decoded (present a <table> with size / waist / hip / inseam ranges in inches — realistic US measurements)\n"
            f"5. <h2> Fit by Body Shape\n"
            f"   <h3> Petite Frame (under 5'4\"): what works, what to avoid, specific length/rise advice\n"
            f"   <h3> Hourglass: how this cut balances hip-to-waist ratio\n"
            f"   <h3> Straight / Athletic Build: how to create the illusion of curves with this {clean_ptype}\n"
            f"   <h3> Curvy / Full-Figured (1X–3X): real notes on hip room, waistband gap, and stretch factor\n"
            f"6. <h2> High Rise vs Mid Rise vs Low Rise — Which Fits Your Body Best? (40 words per rise — who each works for)\n"
            f"7. <h2> The Final Verdict: Buy Your Size or Size Up? (honest recommendation for {display_name} specifically — does it run small, large, or true to size)\n"
            f"8. <p> CTA: shop with confidence, free US shipping on $50+, easy 7-day returns, sizes XS-3X. Do NOT include HTML links.\n"
            f"Target: 800-950 words. Output ONLY clean HTML."
        )

    else:  # outfit_formula
        prompt = base + (
            f"Format: 5-Outfit Formula — Who What Wear / Refinery29 editorial style\n"
            f"Write in HTML:\n"
            f"1. <h1> '{title_hint}'\n"
            f"2. <p> Hook — open with a SPECIFIC insight about this garment's versatility that surprises the reader. NOT 'This piece is so versatile!' — instead: 'The reason the {display_name} works for five completely different occasions is one structural detail most people overlook.' (70 words, first-person stylist voice)\n"
            f"3. Five looks as <h2> sections — each MUST have a creative, evocative occasion title (not generic):\n"
            f"   Required: 'Look 1: [Creative Name]', 'Look 2: [Creative Name]', etc.\n"
            f"   Examples: 'Sunday Farmers Market', 'The Power Lunch', 'Date Night That Doesn\'t Look Like You Tried Too Hard', 'Airport Chic', 'Weekend Gallery Hop'\n"
            f"   Each look (80-90 words) MUST include:\n"
            f"   • Specific top or layer: silhouette + fabric + color (e.g., 'a relaxed linen shirt in ecru, left untucked')\n"
            f"   • A layering piece where relevant: blazer, cardigan, or jacket with specific color/weight\n"
            f"   • Specific bag: style + color (e.g., 'a mini structured tote in chocolate brown')\n"
            f"   • One accessory (belt, earrings, scarf, or hat) with a reason it works\n"
            f"   • Do NOT recommend shoes — MeeeShop sells clothing only\n"
            f"   • One sentence on WHERE exactly to wear this and WHY it works for that context\n"
            f"4. <h2> The Honest Fit Notes (50 words — specific body-type advice: who this works for, who should size up, any length or rise caveat)\n"
            f"5. <p> Direct CTA with price of {display_name}, free US shipping on $50+, 7-day returns. Do NOT include HTML links.\n"
            f"Target: 800-950 words. Output ONLY clean HTML."
        )

    # Append SEO metadata instructions to the prompt so we generate all details in one AI call
    prompt += (
        f"\n\nAt the very end of your response, after the HTML content, you MUST append a `<seometa>` section containing the SEO metadata. The format MUST be exactly like this (use these exact keys):\n"
        f"<seometa>\n"
        f"SEO_TITLE: [50-60 chars, keyword near start, year or 'for Women', compelling — referencing 2026 trend angle if possible]\n"
        f"META_DESC: [140-155 chars, action-oriented, includes keyword, mentions 2026 trend angle or free shipping, ends with CTA]\n"
        f"IMG_ALT: [descriptive ALT text for featured image collage, 10-15 words, describes the outfit/styling scene shown, includes keyword + 'women' + product type, no quotes]\n"
        f"SUGGESTED_HANDLE: [{_slugify(title_hint)}]\n" # Add suggested handle here
        f"</seometa>\n"
        f"Make sure there are no other text or markdown code fences enclosing the <seometa> block."
    )

    return prompt, title_hint

def _extract_h1(html: str, fallback: str) -> str:
    m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.IGNORECASE | re.DOTALL)
    return re.sub(r"<[^>]+>", "", m.group(1)).strip() if m else fallback

def _clean_html(raw: str) -> str:
    raw = raw.strip()
    raw = re.sub(r"^```html?\s*", "", raw, flags=re.IGNORECASE)
    raw = re.sub(r"\s*```$", "", raw)
    raw = re.sub(r"<seometa>.*?</seometa>", "", raw, flags=re.DOTALL | re.IGNORECASE)
    return raw.strip()

def _make_tags(product: dict, fmt: str, keyword: str) -> list[str]:
    base_tags = ["fashion", "women fashion", "MeeeShop", "USA fashion",
                 "women's clothing", "affordable fashion", "style tips"]
    ptype = (product.get("product_type") or "").lower()
    fmt_tags = {
        "buying_guide":   ["buying guide", "fashion guide", f"best picks {YEAR}"],
        "comparison":     ["fashion comparison", "style guide", "what to buy"],
        "problem_solver": ["styling advice", "outfit help", "fashion tips"],
        "trend_report":   [f"fashion trends {YEAR}", "trending styles", "new in fashion"],
        "outfit_formula": ["outfit ideas", "how to style", "outfit inspiration"],
    }
    trending_2026_tags = [
        f"fashion {YEAR}", "denim trends 2026", "quiet luxury",
        "jeans outfit 2026", "summer fashion 2026"
    ]
    tags = base_tags + fmt_tags.get(fmt, []) + trending_2026_tags
    if ptype:
        tags.append(ptype)
    # Denim-specific trending tags
    if any(x in ptype for x in ["jean", "denim"]):
        tags += ["cigarette jeans", "dark wash jeans", "linen top with jeans"]
    # Primary keyword words as tags
    tags += [w for w in keyword.split() if len(w) > 3][:3]
    # Top LSI keywords as tags (short ones work best as Shopify tags)
    lsi = _lsi_keywords(ptype, keyword)
    tags += [k for k in lsi if len(k) < 30][:4]
    return list(dict.fromkeys(tags))[:25]

def clean_product_title(title: str) -> str:
    """Removes formatting chars like *, quotes, and trailing details."""
    t = re.sub(r'[*"\']', '', title)
    t = re.sub(r'\s*\([^)]+\)\s*$', '', t)
    t = re.sub(r'\s*-\s*[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\s*$', '', t)
    return t.strip()

def get_product_display_name(product: dict) -> str:
    """Returns a clean display name with vendor (if not already in title)."""
    vendor = (product.get("vendor") or "").strip()
    title = product.get("title", "").strip()
    clean_title = clean_product_title(title)
    if vendor and vendor.lower() not in clean_title.lower():
        return f"{vendor} {clean_title}"
    return clean_title

def get_clean_product_type(product: dict) -> str:
    """Infers a clean singular product type name from title or type."""
    title = product.get("title", "").lower()
    ptype = (product.get("product_type") or "").lower()
    
    # Specific overrides
    if "skort" in title:
        return "skort"
    if "jort" in title:
        return "jort"
    if "short" in title:
        return "shorts"
    if "jean" in title:
        return "jeans"
    if "denim" in title:
        return "denim"
    if "jacket" in title:
        return "jacket"
    if "coat" in title:
        return "coat"
    if "cardigan" in title:
        return "cardigan"
    if "sweater" in title:
        return "sweater"
    if "dress" in title:
        return "dress"
    if "blouse" in title:
        return "blouse"
    if "shirt" in title:
        return "shirt"
    if "tee" in title or "t-shirt" in title:
        return "t-shirt"
    if "top" in title:
        return "top"
    if "pant" in title:
        return "pants"
    if "skirt" in title:
        return "skirt"
    if "bag" in title or "handbag" in title:
        return "handbag"
        
    # Standardizations
    if "jean" in ptype or "denim" in ptype:
        return "jeans"
    if "dress" in ptype:
        return "dress"
    if "top" in ptype or "blouse" in ptype or "shirt" in ptype:
        return "top"
    if "sweater" in ptype or "cardigan" in ptype or "knit" in ptype:
        return "knitwear"
    if "skirt" in ptype:
        return "skirt"
    if "pant" in ptype:
        return "pants"
    if "bag" in ptype or "handbag" in ptype:
        return "handbag"
        
    return ptype if ptype else "apparel"

def generate_keyword_title_and_format(product: dict, format_override: str = None) -> tuple[str, str, str]:
    display_name = get_product_display_name(product)
    clean_ptype = get_clean_product_type(product)

    # Jeans/denim articles get 2026-trending topic titles
    is_denim = any(x in (product.get("product_type") or "").lower() or (product.get("title") or "").lower()
                   for x in ["jean", "denim"])

    options = [
        (f"{display_name} sizing",
         f"Is {display_name} True to Size? Sizing & Fit Guide for Women {YEAR}",
         "sizing_guide"),
        (f"how to style {display_name}",
         f"5 Stunning Outfits You Can Build Around {display_name} in {YEAR}",
         "outfit_formula"),
        (f"{display_name} review",
         f"The Best {display_name} for Women in {YEAR}: Our Editor's Honest Guide",
         "buying_guide"),
        (f"styling {display_name}",
         f"{MONTH} Women's Fashion Trends: How to Style the {display_name}",
         "trend_report"),
        (f"how to wash {display_name}",
         f"How to Wash and Care for Your {display_name} ({YEAR} Style Guide)",
         "care_guide"),
        (f"{display_name} styling",
         f"How to Style the {display_name} for Casual Chic Outfits (Complete {YEAR} Guide)",
         "problem_solver")
    ]

    # For denim products, add trending 2026 topic options
    if is_denim:
        options += [
            (f"quiet luxury jeans {display_name}",
             f"The Quiet Luxury Denim Look: How to Style {display_name} in {YEAR}",
             "trend_report"),
            (f"how to pair {display_name} summer",
             f"Summer {YEAR} Jeans Outfit Formula: Style {display_name} 5 Ways",
             "outfit_formula"),
        ]

    if format_override:
        matched = [opt for opt in options if opt[2] == format_override]
        if matched:
            return matched[0]

    # Weights: sizing_guide (10%), outfit_formula (25%), buying_guide (20%),
    # trend_report (20%), care_guide (5%), problem_solver (20%)
    base_options = options[:6]
    weights = [0.10, 0.25, 0.20, 0.20, 0.05, 0.20]
    return random.choices(base_options, weights=weights, k=1)[0]

def parse_and_clean_seo_meta(raw_seo_text: str, keyword: str, product_title: str, ptype: str) -> dict:
    """
    Parse SEO title, meta description, and image ALT text from the extracted text block.
    Falls back to deterministic values if parsing fails or fields are missing.
    """
    seo_title = meta_desc = img_alt = suggested_handle = ""

    if raw_seo_text:
        for line in raw_seo_text.splitlines():
            line = line.strip()
            if line.upper().startswith("SEO_TITLE:"):
                seo_title = line.split(":", 1)[1].strip().strip('"')
            elif line.upper().startswith("META_DESC:"):
                meta_desc = line.split(":", 1)[1].strip().strip('"')
            elif line.upper().startswith("IMG_ALT:"):
                img_alt = line.split(":", 1)[1].strip().strip('"')
            elif line.upper().startswith("SUGGESTED_HANDLE:"):
                suggested_handle = line.split(":", 1)[1].strip().strip('"[]')

    # Deterministic fallbacks — always valid even if AI fails
    if not seo_title or len(seo_title) > 70:
        seo_title = f"{keyword.title()} — MeeeShop {YEAR}"[:60]
    if not meta_desc or len(meta_desc) > 165:
        meta_desc = (
            f"Discover the best {ptype} for women in {YEAR}. "
            f"Shop {product_title} at MeeeShop — free US shipping on orders $50+, "
            f"easy 7-day returns, sizes XS–3X."
        )[:155]
    if not img_alt:
        img_alt = f"{product_title} — {ptype} for women, {YEAR} fashion guide at MeeeShop"
    if not suggested_handle:
        suggested_handle = _slugify(seo_title)

    return {
        "seo_title":  seo_title,
        "meta_desc":  meta_desc,
        "img_alt":    img_alt,
        "suggested_handle": suggested_handle,
    }

def product_img_url(product: dict) -> str | None:
    images = product.get("images", [])
    return images[0]["src"] if images else None

def make_product_card(product: dict, keyword: str = "",
                      label: str = "FEATURED PICK — IN STOCK NOW") -> str:
    import html
    raw_title = product["title"]
    escaped_title = html.escape(raw_title)
    price  = product["variants"][0]["price"] if product.get("variants") else "0"
    handle = product.get("handle", "")
    ptype  = (product.get("product_type") or "women's fashion").lower()
    url    = f"{STORE_URL}/products/{handle}?utm_source=blog&utm_medium=featured_card&utm_campaign=meeeshop" if handle else STORE_URL
    img    = product_img_url(product)

    # Keyword-rich ALT text for inline product image
    alt = f"{raw_title} — {ptype} for women at MeeeShop"
    if keyword:
        alt = f"{raw_title} — {keyword}, {ptype} at MeeeShop"

    alt_clean = alt.replace('"', "'")

    img_html = (
        f'<a href="{url}"><img src="{img}" alt="{alt_clean}" '
        f'style="width:220px;height:220px;object-fit:cover;border-radius:10px;flex-shrink:0;" loading="lazy" /></a>'
        if img else ""
    )

    return f"""
<div style="background:#f8f6f3;border-radius:14px;padding:24px 28px;margin:32px 0;
            display:flex;flex-wrap:wrap;gap:24px;align-items:center;
            border:1px solid #eee;font-family:sans-serif;">
  {img_html}
  <div style="flex:1;min-width:200px;">
    <p style="font-size:11px;color:#999;margin:0 0 6px;text-transform:uppercase;letter-spacing:1.5px;font-weight:600;">{label}</p>
    <h3 style="font-size:18px;font-weight:700;margin:0 0 8px;color:#1a1a1a;line-height:1.3;">{escaped_title}</h3>
    <p style="font-size:26px;font-weight:800;color:#1a1a1a;margin:0 0 6px;">${price}</p>
    <p style="font-size:12px;color:#777;margin:0 0 18px;">
      Free US shipping on orders $50+ &nbsp;&bull;&nbsp; 7-day easy returns &nbsp;&bull;&nbsp; Sizes XS–3X
    </p>
    <a href="{url}"
       style="background:#1a1a1a;color:#ffffff;padding:13px 30px;text-decoration:none;
              border-radius:8px;font-size:14px;font-weight:700;letter-spacing:0.5px;
              display:inline-block;">
      Shop Now &rarr;
    </a>
  </div>
</div>
"""

def make_related_products_section(products: list, exclude_handle: str, keyword: str = "", matching_products: list = None) -> str:
    import html
    
    if matching_products:
        picks = matching_products
        section_title = "Shop Styled Pairings from This Article"
        cta_text = "Shop the Look"
    else:
        related = [p for p in products if p.get("handle") != exclude_handle and p.get("images")]
        if not related:
            related = [p for p in products if p.get("handle") != exclude_handle]
        picks = random.sample(related, min(3, len(related)))
        section_title = "You Might Also Love"
        cta_text = "Shop Similar"

    cards_html = ""
    for p in picks:
        raw_title  = p["title"]
        clean_title = clean_product_title(raw_title)
        escaped_title = html.escape(clean_title)
        price  = p["variants"][0]["price"] if p.get("variants") else "0"
        handle = p.get("handle", "")
        ptype  = (p.get("product_type") or "women's fashion").lower()
        url    = f"{STORE_URL}/products/{handle}?utm_source=blog&utm_medium=related_card&utm_campaign=meeeshop"
        img    = product_img_url(p)
        alt    = f"{clean_title} — {ptype} for women at MeeeShop"
        if keyword:
            alt = f"{clean_title} — shop {keyword} at MeeeShop"
        
        alt_clean = alt.replace('"', "'")

        img_tag = (
            f'<a href="{url}"><img src="{img}" alt="{alt_clean}" '
            f'style="width:100%;height:200px;object-fit:cover;border-radius:10px;margin-bottom:12px;" loading="lazy" /></a>'
            if img else ""
        )
        cards_html += f"""
  <div style="flex:1;min-width:200px;max-width:260px;font-family:sans-serif;text-align:center;">
    {img_tag}
    <p style="font-size:14px;font-weight:700;color:#1a1a1a;margin:0 0 4px;line-height:1.3;">{escaped_title}</p>
    <p style="font-size:16px;font-weight:800;color:#1a1a1a;margin:0 0 12px;">${price}</p>
    <a href="{url}"
       style="background:#f0ede8;color:#1a1a1a;padding:9px 20px;text-decoration:none;
              border-radius:6px;font-size:13px;font-weight:600;display:inline-block;">
      {cta_text}
    </a>
  </div>"""

    if not cards_html:
        return ""

    return f"""
<div style="margin:48px 0;padding:32px;background:#fafafa;border-radius:14px;border:1px solid #eee;">
  <h2 style="font-size:20px;font-weight:700;color:#1a1a1a;margin:0 0 24px;text-align:center;">
    {section_title}
  </h2>
  <div style="display:flex;flex-wrap:wrap;gap:24px;justify-content:center;">
    {cards_html}
  </div>
</div>
"""

def inject_product_card(html_body: str, product: dict, keyword: str = "") -> str:
    card = make_product_card(product, keyword)
    insert_after = re.search(r"</h1>\s*(<p>.*?</p>)", html_body, re.DOTALL | re.IGNORECASE)
    if insert_after:
        pos = insert_after.end()
        return html_body[:pos] + "\n" + card + html_body[pos:]
    pos = html_body.find("</p>")
    if pos != -1:
        return html_body[:pos+4] + "\n" + card + html_body[pos+4:]
    return card + html_body

def select_styling_matches(main_product: dict, pool: list, num_matches: int = 2) -> list[dict]:
    main_type = (main_product.get("product_type") or "").lower()
    main_id = main_product.get("id")
    
    # Categorize broad clothing types
    is_top = any(x in main_type for x in ["top", "blouse", "shirt", "tee"])
    is_bottom = any(x in main_type for x in ["jean", "pant", "skirt", "legging", "short"])
    is_one_piece = any(x in main_type for x in ["dress", "jumpsuit", "romper"])
    
    matches = []
    
    # Try to find items of complementary types first
    complementary_pool = []
    for p in pool:
        if p.get("id") == main_id or not p.get("images"):
            continue
        ptype = (p.get("product_type") or "").lower()
        
        if is_top:
            if any(x in ptype for x in ["jean", "pant", "skirt", "jacket", "coat", "cardigan", "accessory"]):
                complementary_pool.append(p)
        elif is_bottom:
            if any(x in ptype for x in ["top", "blouse", "shirt", "tee", "sweater", "jacket", "coat", "cardigan"]):
                complementary_pool.append(p)
        elif is_one_piece:
            if any(x in ptype for x in ["jacket", "coat", "cardigan", "accessory", "shoe", "bag"]):
                complementary_pool.append(p)
        else:
            complementary_pool.append(p)
            
    if len(complementary_pool) >= num_matches:
        matches = random.sample(complementary_pool, num_matches)
    else:
        fallback_pool = [p for p in pool if p.get("id") != main_id and p.get("images")]
        if len(fallback_pool) >= num_matches:
            matches = random.sample(fallback_pool, num_matches)
        else:
            matches = fallback_pool
            
    return matches

def crop_to_fit(img, target_w, target_h):
    """Helper to crop and resize an image to fit target bounds cleanly (center crop)."""
    img_ratio = img.width / img.height
    target_ratio = target_w / target_h
    
    if img_ratio > target_ratio:
        # Image is wider
        new_h = target_h
        new_w = int(img.width * (target_h / img.height))
        img_resized = img.resize((new_w, new_h), Image.Resampling.LANCZOS)
        crop_x = (new_w - target_w) // 2
        return img_resized.crop((crop_x, 0, crop_x + target_w, target_h))
    else:
        # Image is taller
        new_w = target_w
        new_h = int(img.height * (target_w / img.width))
        img_resized = img.resize((new_w, new_h), Image.Resampling.LANCZOS)
        crop_y = (new_h - target_h) // 2
        img_cropped = img_resized.crop((0, crop_y, target_w, crop_y + target_h))
                
            collage.paste(img_cropped, (0, 0))
            
        elif num_imgs == 2:
            spacing = 25
            col_w = (canvas_w - (3 * spacing)) // 2
            col_h = canvas_h - (2 * spacing)
            
            for i, img in enumerate(downloaded_imgs):
                img_resized = crop_to_fit(img, col_w, col_h)
                left = spacing + i * (col_w + spacing)
                top = spacing
                collage.paste(img_resized, (left, top))
                
        else:
            spacing = 20
            col_w = (canvas_w - (4 * spacing)) // 3
            col_h = canvas_h - (2 * spacing)
            
            for i, img in enumerate(downloaded_imgs[:3]):
                img_resized = crop_to_fit(img, col_w, col_h)
                left = spacing + i * (col_w + spacing)
                top = spacing
                collage.paste(img_resized, (left, top))
                
        temp_path = Path("collage_temp.jpg")
        collage.save(temp_path, "JPEG", quality=92)
        print(f"  ✓ Collage generated locally: {temp_path.absolute()}")
        return temp_path
    except Exception as e:
        print(f"  [!] Failed to generate image collage: {e}")
        return None

def upload_image_to_shopify(filepath: Path, filename: str) -> str | None:
    """Uploads the generated collage to Shopify Files and fetches its CDN URL."""
    print(f"  Uploading {filename} to Shopify Files...")
    graphql_url = f"{BASE}/graphql.json"
    
    staged_mut = f"""
    mutation {{
      stagedUploadsCreate(input: [{{
        resource: FILE,
        filename: "{filename}",
        mimeType: "image/jpeg",
        httpMethod: POST
      }}]) {{
        stagedTargets {{
          url
          resourceUrl
          parameters {{
            name
            value
          }}
        }}
      }}
    }}
    """
    try:
        r = _req("post", graphql_url, json={"query": staged_mut})
        r.raise_for_status()
        data = r.json()
        target = data["data"]["stagedUploadsCreate"]["stagedTargets"][0]
        
        # Upload the file to staging
        with open(filepath, "rb") as f:
            files = {"file": (filename, f, "image/jpeg")}
            params = {p["name"]: p["value"] for p in target["parameters"]}
            upload_resp = requests.post(target["url"], data=params, files=files, timeout=30)
            upload_resp.raise_for_status()
            
        # Create file reference in Shopify
        create_mut = """
        mutation fileCreate($files: [FileCreateInput!]!) {
          fileCreate(files: $files) {
            files {
              id
              fileStatus
            }
            userErrors {
              message
            }
          }
        }
        """
        variables = {
            "files": [
                {
                    "originalSource": target["resourceUrl"],
                    "contentType": "FILE"
                }
            ]
        }
        r = _req("post", graphql_url, json={"query": create_mut, "variables": variables})
        r.raise_for_status()
        create_data = r.json()
        
        user_errors = create_data.get("data", {}).get("fileCreate", {}).get("userErrors", [])
        if user_errors:
            print(f"  [!] Shopify fileCreate user errors: {user_errors}")
            return None
            
        file_id = create_data["data"]["fileCreate"]["files"][0]["id"]
        
        # Wait for file compilation
        public_url = None
        for _ in range(15):
            time.sleep(2)
            query_file = f"""
            query {{
              node(id: "{file_id}") {{
                ... on GenericFile {{
                  url
                  fileStatus
                }}
              }}
            }}
            """
            r = _req("post", graphql_url, json={"query": query_file})
            r.raise_for_status()
            node_data = r.json()
            node = node_data.get("data", {}).get("node", {})
            if node.get("fileStatus") == "READY":
                public_url = node.get("url")
                break
                
        if public_url:
            cdn_url = public_url.split("?")[0]
            print(f"  ✓ Uploaded successfully: {cdn_url}")
            return cdn_url
        else:
            print("  [!] Timeout waiting for image compilation on Shopify CDN.")
            return None
    except Exception as e:
        print(f"  [!] Failed to upload image to Shopify: {e}")
        return None

def get_all_blogs() -> list:
    r = _req("get", f"{BASE}/blogs.json")
    r.raise_for_status()
    return r.json().get("blogs", [])

def get_or_create_blog(product_type: str, all_blogs: list, dry_run: bool = False) -> dict:
    ptype_lower = (product_type or "").lower()
    
    # 1. Direct target blog names mapping
    target_blog_title = None
    if "dress" in ptype_lower:
        target_blog_title = "dresses"
    elif any(x in ptype_lower for x in ["jean", "denim", "jort"]):
        target_blog_title = "jeans"
    elif any(x in ptype_lower for x in ["skirt", "skort"]):
        target_blog_title = "skirts"
    elif any(x in ptype_lower for x in ["pant", "legging", "short"]):
        target_blog_title = "pants"
    elif any(x in ptype_lower for x in ["top", "blouse", "shirt", "tee", "t-shirt", "tank"]):
        target_blog_title = "shirts & tops"
    elif any(x in ptype_lower for x in ["jacket", "coat", "outerwear", "blazer"]):
        target_blog_title = "coats & jackets"
    elif any(x in ptype_lower for x in ["sweater", "cardigan", "knit", "pullover"]):
        target_blog_title = "cardigans & sweaters"
        
    # 2. Try matching the targeted title
    if target_blog_title:
        for blog in all_blogs:
            title_lower = blog.get("title", "").lower()
            # Avoid matching Announcements or system blogs
            if "announcements" in title_lower or "tips" in title_lower:
                continue
            if target_blog_title in title_lower:
                return blog
                
    # 3. Fallback to "Women's Clothing" if available
    for blog in all_blogs:
        title_lower = blog.get("title", "").lower()
        if "women's clothing" in title_lower:
            return blog
            
    # 4. Fallback to any blog that is not a system blog
    non_system_blogs = [
        b for b in all_blogs 
        if "announcements" not in b.get("title", "").lower() and "tips" not in b.get("title", "").lower()
    ]
    if non_system_blogs:
        return non_system_blogs[0]
        
    if all_blogs:
        return all_blogs[0]
        
    if dry_run:
        return {"id": 0, "title": "MOCK Fallback Blog (Dry Run)"}
        
    # Create blog if none exist
    r = _req("post", f"{BASE}/blogs.json",
             json={"blog": {"title": "Women's Clothing"}})
    r.raise_for_status()
    new_blog = r.json()["blog"]
    all_blogs.append(new_blog)
    return new_blog

def set_article_seo_metafields(blog_id: int, article_id: int, seo_title: str, meta_desc: str):
    """
    Set SEO title and meta description via Shopify metafields.
    These map to the <title> tag and <meta name="description"> in Shopify themes.
    Namespace: global — keys: title_tag, description_tag (standard Shopify SEO metafields).
    """
    metafields = [
        {"namespace": "global", "key": "title_tag",       "value": seo_title, "type": "single_line_text_field"},
        {"namespace": "global", "key": "description_tag", "value": meta_desc, "type": "single_line_text_field"},
    ]
    for mf in metafields:
        # Check if metafield exists to update, otherwise create
        existing_metafields = _req("get", f"{BASE}/blogs/{blog_id}/articles/{article_id}/metafields.json").json().get("metafields", [])
        existing_mf = next((m for m in existing_metafields if m["namespace"] == mf["namespace"] and m["key"] == mf["key"]), None)

        if existing_mf:
            r = _req("put",
                     f"{BASE}/blogs/{blog_id}/articles/{article_id}/metafields/{existing_mf['id']}.json",
                     json={"metafield": {"id": existing_mf["id"], "value": mf["value"]}})
        else:
            r = _req("post",
                     f"{BASE}/blogs/{blog_id}/articles/{article_id}/metafields.json",
                     json={"metafield": mf})

        if r.status_code in (200, 201):
            print(f"  SEO metafield set: {mf['key']} = {mf['value'][:60]}")
        else:
            print(f"  SEO metafield FAILED ({mf['key']}): {r.status_code} {r.text[:100]}")


# ── New functions for this script ──────────────────────────────────────────────
def fetch_all_products_with_images() -> list:
    """Fetch all products that have at least one image."""
    products, page_info = [], None
    while True:
        params = {
            "limit": 250,
            "fields": "id,title,handle,product_type,variants,images,vendor",
        }
        if page_info:
            params["page_info"] = page_info
        r = _req("get", f"{BASE}/products.json", params=params)
        r.raise_for_status()
        batch = r.json().get("products", [])
        products.extend([p for p in batch if p.get("images")]) # Only add products with images
        link = r.headers.get("Link", "")
        m = re.search(r'<[^>]*page_info=([^&>]+)[^>]*>;\s*rel="next"', link)
        if m:
            page_info = m.group(1)
        else:
            break
    return products

def fetch_all_articles_with_blog_info(article_id: int | None = None) -> list:
    """
    Fetches all articles from all blogs, attaching blog_id and blog_handle.
    If article_id is provided, fetches only that specific article.
    """
    all_blogs = get_all_blogs()
    all_articles = []

    for blog in all_blogs:
        blog_id = blog["id"]
        blog_handle = blog["handle"]
        
        if article_id:
            # Fetch specific article
            try:
                r = _req("get", f"{BASE}/blogs/{blog_id}/articles/{article_id}.json")
                r.raise_for_status()
                article = r.json().get("article")
                if article:
                    article["_blog_id"] = blog_id
                    article["_blog_handle"] = blog_handle
                    all_articles.append(article)
                    return all_articles # Found the article, return it
            except requests.exceptions.HTTPError as e:
                if e.response.status_code == 404:
                    continue # Article not in this blog, try next
                raise
        else:
            # Fetch all articles for this blog
            page_info = None
            while True:
                params = {"limit": 250, "fields": "id,title,handle,body_html,image,tags,summary_html,published_at,author"}
                if page_info:
                    params["page_info"] = page_info
                r = _req("get", f"{BASE}/blogs/{blog_id}/articles.json", params=params)
                r.raise_for_status()
                batch = r.json().get("articles", [])
                if not batch:
                    break
                for article in batch:
                    article["_blog_id"] = blog_id
                    article["_blog_handle"] = blog_handle
                    all_articles.append(article)
                link = r.headers.get("Link", "")
                m = re.search(r'<[^>]*page_info=([^&>]+)[^>]*>;\s*rel="next"', link)
                if m:
                    page_info = m.group(1)
                else:
                    break
    return all_articles

def create_redirect(old_full_url: str, new_full_url: str, dry_run: bool) -> bool:
    """
    Creates a 301 redirect from old_full_url to new_full_url.
    Checks if redirect already exists to prevent duplicates.
    """
    # Extract path from full URLs
    old_path = urlparse(old_full_url).path
    new_target = new_full_url # Shopify redirect target can be a full URL

    # Check for existing redirect
    try:
        r = _req("get", f"{BASE}/redirects.json?path={quote(old_path)}")
        r.raise_for_status()
        existing_redirects = r.json().get("redirects", [])
        for redirect in existing_redirects:
            if redirect["path"] == old_path and redirect["target"] == new_target:
                print(f"    [Redirect] Existing redirect found for '{old_path}' -> '{new_target}'. Skipping.")
                return False
    except Exception as e:
        print(f"    [Redirect] Error checking existing redirects for path '{old_path}': {e}")
        # Continue to attempt creation if check fails

    if dry_run:
        print(f"    [DRY-RUN] Would create redirect: '{old_path}' -> '{new_target}'")
        return True

    try:
        payload = {
            "redirect": {
                "path": old_path,
                "target": new_target
            }
        }
        r = _req("post", f"{BASE}/redirects.json", json=payload)
        r.raise_for_status()
        print(f"    [Redirect] Created redirect: '{old_path}' -> '{new_target}'")
        return True
    except Exception as e:
        print(f"    [Redirect] Failed to create redirect for '{old_path}' -> '{new_target}': {e}")
        return False

def regenerate_single_article(
    original_article: dict,
    all_products_with_images: list,
    all_blogs: list,
    dry_run: bool,
    force_format: str | None = None
) -> dict:
    """
    Regenerates content for a single article, handles redirects, and updates Shopify.
    Returns a dictionary with status and details.
    """
    blog_id = original_article["_blog_id"]
    blog_handle = original_article["_blog_handle"]
    article_id = original_article["id"]
    original_title = original_article["title"]
    original_handle = original_article["handle"]
    original_tags = original_article.get("tags", "")
    
    log_entry = {
        "article_id": article_id,
        "original_title": original_title,
        "original_handle": original_handle,
        "status": "skipped",
        "changes": []
    }

    print(f"\nProcessing article: '{original_title}' (ID: {article_id}, Handle: {original_handle})")

    # 1. Select a relevant product for the article
    # Try to pick a product whose type or title keywords match the article title
    product_pool_for_selection = [p for p in all_products_with_images if p.get("images")]
    if not product_pool_for_selection:
        print("  [ERROR] No products with images available for selection. Skipping article.")
        log_entry["status"] = "error"
        log_entry["message"] = "No products with images for regeneration"
        return log_entry

    selected_product = None
    # Attempt to find a product whose type matches the article title
    for ptype_keyword in ["jean", "dress", "skirt", "top", "pant", "jacket", "coat", "sweater", "cardigan", "swimwear", "activewear", "accessory"]:
        if ptype_keyword in original_title.lower():
            matching_products = [p for p in product_pool_for_selection if ptype_keyword in (p.get("product_type") or "").lower()]
            if matching_products:
                selected_product = random.choice(matching_products)
                break
    
    if not selected_product:
        # Fallback: pick a random product from the pool
        selected_product = random.choice(product_pool_for_selection)

    print(f"  Selected product for regeneration: '{selected_product['title']}' (Type: {selected_product.get('product_type')})")

    # 2. Generate keyword, title hint, and format
    keyword, title_hint, fmt = generate_keyword_title_and_format(selected_product, format_override=force_format)
    print(f"  Generated format: {fmt} | Keyword: '{keyword}' | Title Hint: '{title_hint}'")

    # 3. Select styling matches for collage and prompt
    matching_products = select_styling_matches(selected_product, all_products_with_images, num_matches=2)
    print(f"  Matching products for collage: {[p['title'] for p in matching_products]}")

    # 4. Build AI prompt and generate content
    prompt, _ = _build_prompt(fmt, selected_product, keyword, title_hint, similar_products=all_products_with_images, matching_products=matching_products)
    print("  Generating new content with AI...")
    raw_ai_response = ai_client.generate(prompt, max_tokens=2000, temperature=0.75)

    if not raw_ai_response:
        print("  [ERROR] AI content generation failed. Skipping article.")
        log_entry["status"] = "error"
        log_entry["message"] = "AI content generation failed"
        return log_entry

    html_body = _clean_html(raw_ai_response)
    seo_meta = parse_and_clean_seo_meta(raw_ai_response, keyword, selected_product["title"], get_clean_product_type(selected_product))
    
    new_title = _extract_h1(html_body, seo_meta["seo_title"])
    suggested_handle = seo_meta["suggested_handle"]
    
    # Ensure suggested_handle is not empty
    if not suggested_handle:
        suggested_handle = _slugify(new_title)
        seo_meta["suggested_handle"] = suggested_handle

    # 5. Generate and upload featured image collage
    img_url = None
    collage_path = generate_outfit_collage(selected_product, matching_products)
    if collage_path and collage_path.exists():
        if not dry_run:
            ts = int(time.time())
            filename = f"regenerated_collage_{article_id}_{ts}.jpg"
            img_url = upload_image_to_shopify(collage_path, filename)
            try:
                collage_path.unlink()
            except Exception:
                pass
        else:
            img_url = f"file:///{collage_path.absolute().as_posix()}"
    if not img_url:
        print("  [WARN] Collage creation/upload failed, falling back to single product image URL.")
        img_url = product_img_url(selected_product) # Fallback to single product image

    # 6. Inject product cards and related products section
    html_body = inject_product_card(html_body, selected_product, keyword)
    html_body += make_related_products_section(all_products_with_images, selected_product.get("handle", ""), keyword, matching_products)

    # 7. Generate tags
    new_tags = _make_tags(selected_product, fmt, keyword)
    # Merge with original tags, ensuring uniqueness and limit
    original_tags_list = [t.strip() for t in original_tags.split(',') if t.strip()]
    new_tags = list(dict.fromkeys(new_tags + original_tags_list))[:25]

    # 8. Handle comparison and redirect
    final_handle = original_handle
    if suggested_handle != original_handle:
        print(f"  [HANDLE CHANGE] Suggested handle '{suggested_handle}' differs from original '{original_handle}'.")
        old_full_url = f"{STORE_URL}/blogs/{blog_handle}/{original_handle}"
        new_full_url = f"{STORE_URL}/blogs/{blog_handle}/{suggested_handle}" # Assuming blog_handle remains same
        if not dry_run:
            if create_redirect(old_full_url, new_full_url, dry_run=False):
                final_handle = suggested_handle
                log_entry["changes"].append({"field": "handle", "old": original_handle, "new": suggested_handle, "redirect_created": True})
            else:
                print(f"    [WARN] Failed to create redirect. Keeping original handle: '{original_handle}'.")
                log_entry["changes"].append({"field": "handle", "old": original_handle, "new": original_handle, "redirect_created": False, "message": "Redirect failed"})
        else:
            print(f"    [DRY-RUN] Would change handle to '{suggested_handle}' and create redirect from '{old_full_url}' to '{new_full_url}'.")
            final_handle = suggested_handle # For dry-run output
            log_entry["changes"].append({"field": "handle", "old": original_handle, "new": suggested_handle, "redirect_created": True, "dry_run": True})
    else:
        print(f"  [HANDLE] Handle remains unchanged: '{original_handle}'.")

    # 9. Prepare payload for article update
    payload = {
        "title": new_title,
        "author": random.choice(PEN_NAMES), # Assign a new E-E-A-T author
        "body_html": html_body,
        "summary_html": seo_meta["meta_desc"],
        "tags": ", ".join(new_tags),
        "handle": final_handle,
        "published": original_article.get("published", True), # Keep original published status
    }
    if img_url:
        payload["image"] = {
            "src": img_url,
            "alt": seo_meta["img_alt"],
        }
    
    if new_title != original_title:
        log_entry["changes"].append({"field": "title", "old": original_title, "new": new_title})
    if original_article.get("body_html") != html_body:
        log_entry["changes"].append({"field": "body_html", "old_len": len(original_article.get("body_html", "")), "new_len": len(html_body)})
    if original_article.get("image", {}).get("src") != img_url:
        log_entry["changes"].append({"field": "image_src", "old": original_article.get("image", {}).get("src"), "new": img_url})
    if original_article.get("image", {}).get("alt") != seo_meta["img_alt"]:
        log_entry["changes"].append({"field": "image_alt", "old": original_article.get("image", {}).get("alt"), "new": seo_meta["img_alt"]})
    if original_article.get("tags") != payload["tags"]:
        log_entry["changes"].append({"field": "tags", "old": original_tags, "new": payload["tags"]})
    if original_article.get("author") != payload["author"]:
        log_entry["changes"].append({"field": "author", "old": original_article.get("author"), "new": payload["author"]})

    # 10. Perform update
    if dry_run:
        print(f"  [DRY-RUN] Would update article {article_id} with new content and metadata.")
        print(f"    New Title: {new_title}")
        print(f"    New Handle: {final_handle}")
        print(f"    New Image: {img_url}")
        print(f"    New Tags: {', '.join(new_tags)}")
        log_entry["status"] = "dry_run_success"
    else:
        try:
            # Save a backup of the original article content before we edit it
            backup_data = {
                "article_id": article_id,
                "title": original_title,
                "handle": original_handle,
                "body_html": original_article.get("body_html", ""),
                "summary_html": original_article.get("summary_html", ""),
                "tags": original_tags,
                "image": original_article.get("image", {}),
                "author": original_article.get("author", ""),
                "published_at": original_article.get("published_at", ""),
                "backup_timestamp": datetime.now().isoformat()
            }
            backup_dir = REPO_ROOT / "backup_articles"
            backup_dir.mkdir(exist_ok=True)
            backup_file = backup_dir / f"article_{article_id}_{int(time.time())}.json"
            backup_file.write_text(json.dumps(backup_data, indent=2, ensure_ascii=False), encoding="utf-8")
            print(f"    [Backup] Saved original article content to backup_articles/{backup_file.name}")

            updated_article = _req("put", f"{BASE}/blogs/{blog_id}/articles/{article_id}.json", json={"article": payload}).json().get("article")
            if updated_article:
                print(f"  ✓ Successfully updated article {article_id}.")
                # Set SEO metafields
                set_article_seo_metafields(blog_id, article_id, seo_meta["seo_title"], seo_meta["meta_desc"])
                log_entry["status"] = "success"
            else:
                raise RuntimeError("Shopify update returned no article data.")
        except Exception as e:
            print(f"  [ERROR] Failed to update article {article_id}: {e}")
            log_entry["status"] = "error"
            log_entry["message"] = str(e)
            
    return log_entry

def main():
    parser = argparse.ArgumentParser(description="Regenerate content for existing Shopify blog articles.")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing to Shopify.")
    parser.add_argument("--force", action="store_true", help="Process ALL existing articles.")
    parser.add_argument("--article-id", type=int, default=None, help="Process a single specific article by ID.")
    parser.add_argument("--batch-size", type=int, default=20, help="Number of articles to process per batch in --force mode.")
    parser.add_argument("--batch-index", type=int, default=0, help="0-based index of the batch to process in --force mode.")
    parser.add_argument("--count-only", action="store_true", help="Print total number of articles to process and exit (for CI matrix).")
    parser.add_argument("--force-format", type=str, default=None,
                        choices=FORMATS,
                        help="Force a specific blog format for all regenerated articles.")
    args = parser.parse_args()

    print(f"\n{'='*70}")
    print(f"  MeeeShop Article Regenerator — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"  Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    print(f"  Scope: {'ALL articles' if args.force else (f'Article ID: {args.article_id}' if args.article_id else 'Default (not implemented yet)')}")
    if args.force:
        print(f"  Batch: {args.batch_index} of size {args.batch_size}")
    if args.force_format:
        print(f"  Forced Format: {args.force_format}")
    print(f"{'='*70}\n")

    all_products_with_images = fetch_all_products_with_images()
    if not all_products_with_images:
        sys.exit("ERROR: No products with images found in Shopify. Cannot regenerate articles.")
    print(f"Loaded {len(all_products_with_images)} products with images for content generation.")

    all_articles = fetch_all_articles_with_blog_info(args.article_id)
    if not all_articles:
        sys.exit("ERROR: No articles found to process.")
    
    if args.count_only:
        print(len(all_articles))
        return

    articles_to_process = []
    if args.article_id:
        articles_to_process = [a for a in all_articles if a["id"] == args.article_id]
        if not articles_to_process:
            sys.exit(f"ERROR: Article with ID {args.article_id} not found.")
    elif args.force:
        start_index = args.batch_index * args.batch_size
        end_index = start_index + args.batch_size
        articles_to_process = all_articles[start_index:end_index]
        print(f"Processing batch {args.batch_index}: articles {start_index} to {end_index-1} out of {len(all_articles)} total.")
    else:
        # Default mode if not --force or --article-id: process a small number of oldest articles
        # For now, let's make it explicit that --force or --article-id is required.
        sys.exit("ERROR: Please specify --force to process all articles or --article-id to process a single article.")

    if not articles_to_process:
        print("No articles selected for processing in this run.")
        return

    results = []
    for article in articles_to_process:
        result = regenerate_single_article(article, all_products_with_images, get_all_blogs(), args.dry_run, args.force_format)
        results.append(result)
        time.sleep(2) # Be kind to APIs

    print(f"\n{'='*70}")
    print("Regeneration Summary:")
    print(f"Total articles attempted: {len(results)}")
    print(f"Successful: {sum(1 for r in results if r['status'] == 'success' or r['status'] == 'dry_run_success')}")
    print(f"Errors: {sum(1 for r in results if r['status'] == 'error')}")
    print(f"{'='*70}\n")

    # Save detailed log
    log_filename = f"regenerate_articles_log_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(LOG_DIR / log_filename, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    print(f"Detailed log saved to {LOG_DIR / log_filename}")

if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    main()